# Generated by Django 6.0.3 on 2026-06-09 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimetableEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(verbose_name="일자")),
                ("start_time", models.TimeField(verbose_name="시작")),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="종료"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                (
                    "location",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="장소"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="설명"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="정렬"),
                ),
            ],
            options={
                "verbose_name": "타임테이블",
                "verbose_name_plural": "타임테이블",
                "ordering": ["day", "start_time", "sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("body", models.TextField(verbose_name="내용")),
                (
                    "is_pinned",
                    models.BooleanField(default=False, verbose_name="상단 고정"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notices_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "공지사항",
                "verbose_name_plural": "공지사항",
                "ordering": ["-is_pinned", "-created_at"],
            },
        ),
    ]
