# Generated by Django 6.0.3 on 2026-06-09 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notices", "0002_seed_timetable_sample"),
        ("users", "0013_user_signup_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="division",
            field=models.ForeignKey(
                blank=True,
                help_text="공개 범위가 '지역·부서'일 때 대상 부서. '전체'면 비워 둔다.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notices",
                to="users.division",
                verbose_name="대상 부서",
            ),
        ),
        migrations.AddField(
            model_name="notice",
            name="scope",
            field=models.CharField(
                choices=[("all", "전체"), ("division", "지역·부서")],
                default="all",
                max_length=16,
                verbose_name="공개 범위",
            ),
        ),
    ]
