# Generated by Django 6.0.3 on 2026-06-16 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notices", "0003_notice_division_notice_scope"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoticeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="이름")),
                ("slug", models.SlugField(unique=True, verbose_name="슬러그")),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="pill 배지 색상(hex, 예: #4a9eff). 비우면 기본색.",
                        max_length=7,
                        verbose_name="색상",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="정렬"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
            ],
            options={
                "verbose_name": "공지 카테고리",
                "verbose_name_plural": "공지 카테고리",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="notice",
            name="tags",
            field=models.CharField(
                blank=True,
                default="",
                help_text="쉼표로 구분 (예: 수련회,청년부)",
                max_length=500,
                verbose_name="태그",
            ),
        ),
        migrations.AddField(
            model_name="notice",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="목록 카드·상세 배너 이미지",
                null=True,
                upload_to="notices/",
                verbose_name="썸네일",
            ),
        ),
        migrations.AddField(
            model_name="notice",
            name="view_count",
            field=models.PositiveIntegerField(default=0, verbose_name="조회수"),
        ),
        migrations.AddField(
            model_name="notice",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notices",
                to="notices.noticecategory",
                verbose_name="카테고리",
            ),
        ),
    ]
