# Generated by Django 6.0.3 on 2026-07-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notices", "0004_notice_category_and_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaqItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=300, verbose_name="질문")),
                ("answer", models.TextField(verbose_name="답변")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="정렬"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQ",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
