# Generated by Django 6.0.3 on 2026-03-22 16:19

import django.db.models.deletion
import users.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="이름")),
                (
                    "name_alias",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="별칭·통칭"
                    ),
                ),
                (
                    "import_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="엑셀 등 병합용",
                        max_length=64,
                        verbose_name="임포트 키",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최초 등록자",
                    ),
                ),
                (
                    "linked_user",
                    models.OneToOneField(
                        blank=True,
                        help_text="회원가입 후 교적과 연결할 때만 사용",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_member_record",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="연결된 앱 계정",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최종 수정자",
                    ),
                ),
            ],
            options={
                "verbose_name": "교적(멤버)",
                "verbose_name_plural": "교적(멤버)",
                "db_table": "users_member",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MemberClub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="정렬 순서"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_club_memberships",
                        to="users.club",
                        verbose_name="동아리",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_clubs",
                        to="registry.member",
                        verbose_name="멤버(교적)",
                    ),
                ),
            ],
            options={
                "verbose_name": "교적 동아리 소속",
                "verbose_name_plural": "교적 동아리 소속",
                "db_table": "users_memberclub",
                "ordering": ["member", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="MemberDivisionTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="주 소속"),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="정렬 순서"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_division_teams",
                        to="users.division",
                        verbose_name="부서",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="division_teams",
                        to="registry.member",
                        verbose_name="멤버(교적)",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_division_teams",
                        to="users.team",
                        verbose_name="팀",
                    ),
                ),
            ],
            options={
                "verbose_name": "교적 부서·팀 소속",
                "verbose_name_plural": "교적 부서·팀 소속",
                "db_table": "users_memberdivisionteam",
                "ordering": ["member", "-is_primary", "division", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="MemberFamilyMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="이름")),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("father", "부"),
                            ("mother", "모"),
                            ("spouse", "배우자"),
                            ("elder_brother", "형/오빠"),
                            ("younger_brother", "남동생"),
                            ("elder_sister", "언니/누나"),
                            ("younger_sister", "여동생"),
                            ("son", "아들"),
                            ("daughter", "딸"),
                            ("other", "기타"),
                        ],
                        default="other",
                        max_length=30,
                        verbose_name="관계",
                    ),
                ),
                (
                    "relationship_note",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="기타 선택 시 또는 세부 표기",
                        max_length=50,
                        verbose_name="관계(직접입력)",
                    ),
                ),
                (
                    "affiliation_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="예: 광명교구, 청년부, 불신",
                        max_length=100,
                        verbose_name="소속",
                    ),
                ),
                (
                    "church_position",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="직분"
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, default="", verbose_name="비고"),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="정렬 순서"
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        blank=True,
                        help_text="카드 표기와 맞출 때만 연결",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="member_family_affiliations",
                        to="users.division",
                        verbose_name="소속 부서(선택)",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_members",
                        to="registry.member",
                        verbose_name="멤버",
                    ),
                ),
            ],
            options={
                "verbose_name": "멤버 가족",
                "verbose_name_plural": "멤버 가족",
                "db_table": "users_memberfamilymember",
                "ordering": ["member", "sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="MemberFunctionalDeptRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="정렬 순서"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "functional_department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_roles",
                        to="users.functionaldepartment",
                        verbose_name="일하는 부서",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="functional_dept_roles",
                        to="registry.member",
                        verbose_name="멤버(교적)",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="member_functional_roles",
                        to="users.role",
                        verbose_name="직책",
                    ),
                ),
            ],
            options={
                "verbose_name": "교적 일하는 부서 직책",
                "verbose_name_plural": "교적 일하는 부서 직책",
                "db_table": "users_memberfunctionaldeptrole",
                "ordering": ["member", "functional_department", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="MemberProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="생년월일"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="교적부용. 앱 프로필 휴대폰과 별개일 수 있음.",
                        max_length=30,
                        validators=[users.validators.validate_korea_mobile_phone],
                        verbose_name="연락처(교적)",
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, default="", verbose_name="주소"),
                ),
                (
                    "church_position_display",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="직분·직책(카드)",
                    ),
                ),
                (
                    "workplace_display",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="직장(업무)",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="members/profile/",
                        verbose_name="사진",
                    ),
                ),
                (
                    "family_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="members/family/",
                        verbose_name="가족 사진",
                    ),
                ),
                (
                    "staff_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="관리자·목회진만 열람",
                        verbose_name="목회 메모",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최초 등록자",
                    ),
                ),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pastoral_profile",
                        to="registry.member",
                        verbose_name="멤버(교적)",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최종 수정자",
                    ),
                ),
            ],
            options={
                "verbose_name": "교적 프로필",
                "verbose_name_plural": "교적 프로필",
                "db_table": "users_memberprofile",
            },
        ),
        migrations.CreateModel(
            name="MemberVisitLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visit_date",
                    models.DateField(
                        help_text="매주 통화면 해당 주 대표일(예: 통화한 날)",
                        verbose_name="심방일(기준일)",
                    ),
                ),
                (
                    "contact_method",
                    models.CharField(
                        choices=[
                            ("phone", "전화"),
                            ("visit", "방문"),
                            ("other", "기타"),
                        ],
                        default="phone",
                        max_length=20,
                        verbose_name="방식",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="상황, 대화 요약 등", verbose_name="내용"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visit_logs",
                        to="registry.member",
                        verbose_name="멤버",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_member_visits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="기록자",
                    ),
                ),
            ],
            options={
                "verbose_name": "멤버 심방 기록",
                "verbose_name_plural": "멤버 심방 기록",
                "db_table": "users_membervisitlog",
                "ordering": ["-visit_date", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(fields=["name"], name="users_membe_name_d53d4b_idx"),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(
                fields=["import_key"], name="users_membe_import__45806c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="memberclub",
            unique_together={("member", "club")},
        ),
        migrations.AddConstraint(
            model_name="memberdivisionteam",
            constraint=models.UniqueConstraint(
                fields=("member", "division", "team"),
                name="unique_member_division_team",
            ),
        ),
        migrations.AddConstraint(
            model_name="memberfunctionaldeptrole",
            constraint=models.UniqueConstraint(
                fields=("member", "functional_department", "role"),
                name="unique_member_funcdept_role",
            ),
        ),
        migrations.AddIndex(
            model_name="membervisitlog",
            index=models.Index(
                fields=["member", "-visit_date"], name="users_membe_member__a5dfff_idx"
            ),
        ),
    ]
