# Generated by Django 6.0.3 on 2026-03-23 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="linked_user",
            field=models.OneToOneField(
                blank=True,
                help_text="회원가입 계정과 연결 시 사용. 연결되어 있으면 교적의 부서·팀(MemberDivisionTeam) 변경 시 같은 부서 범위에서 UserDivisionTeam 이 자동으로 맞춰집니다.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_member_record",
                to=settings.AUTH_USER_MODEL,
                verbose_name="연결된 앱 계정",
            ),
        ),
        migrations.AlterField(
            model_name="memberdivisionteam",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="member_division_teams",
                to="users.team",
                verbose_name="팀",
            ),
        ),
    ]
