# renew_before_expiry = 30 days
version = 2.11.0
archive_dir = /etc/letsencrypt/archive/shalom.docs.jcc-seoul.com
cert = /etc/letsencrypt/live/shalom.docs.jcc-seoul.com/cert.pem
privkey = /etc/letsencrypt/live/shalom.docs.jcc-seoul.com/privkey.pem
chain = /etc/letsencrypt/live/shalom.docs.jcc-seoul.com/chain.pem
fullchain = /etc/letsencrypt/live/shalom.docs.jcc-seoul.com/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 19a35379200ef437077182a8a493429a
rsa_key_size = 2048
key_type = ecdsa
elliptic_curve = secp256r1
pref_challs = dns-01,
server = https://acme-v02.api.letsencrypt.org/directory
authenticator = dns-route53
