# renew_before_expiry = 30 days
version = 2.11.0
archive_dir = /etc/letsencrypt/archive/shalom.jcc-seoul.com
cert = /etc/letsencrypt/live/shalom.jcc-seoul.com/cert.pem
privkey = /etc/letsencrypt/live/shalom.jcc-seoul.com/privkey.pem
chain = /etc/letsencrypt/live/shalom.jcc-seoul.com/chain.pem
fullchain = /etc/letsencrypt/live/shalom.jcc-seoul.com/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 201d50fb5f6fc51d230ed3e6a645942d
key_type = ecdsa
authenticator = dns-route53
server = https://acme-v02.api.letsencrypt.org/directory
