# Generated by Django 6.0.3 on 2026-06-02 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("registry", "0003_memberdivisionteam_one_team_per_division"),
        ("users", "0009_region_and_division_region"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RetreatEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="행사명")),
                ("start_date", models.DateField(verbose_name="시작일")),
                ("end_date", models.DateField(verbose_name="종료일")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="비활성화 시 API 목록/관리 화면에서 숨김(데이터는 보존).",
                        verbose_name="활성",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "수련회 행사",
                "verbose_name_plural": "수련회 행사",
                "ordering": ["-start_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RetreatGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="예: '1조'", max_length=50, verbose_name="조 이름"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="정렬 순서"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retreat_groups",
                        to="users.division",
                        verbose_name="부서",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="retreat.retreatevent",
                        verbose_name="행사",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retreat_groups",
                        to="users.region",
                        verbose_name="지역",
                    ),
                ),
            ],
            options={
                "verbose_name": "수련회 조",
                "verbose_name_plural": "수련회 조",
                "ordering": [
                    "event",
                    "region__sort_order",
                    "division__sort_order",
                    "order",
                    "id",
                ],
            },
        ),
        migrations.CreateModel(
            name="RetreatAttendee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, verbose_name="이름")),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="연락처"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "남성"), ("female", "여성"), ("", "미지정")],
                        default="",
                        max_length=10,
                        verbose_name="성별",
                    ),
                ),
                (
                    "memo",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="메모"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="정렬 순서"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retreat_attendees",
                        to="registry.member",
                        verbose_name="교적 연결",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendees",
                        to="retreat.retreatgroup",
                        verbose_name="조",
                    ),
                ),
            ],
            options={
                "verbose_name": "수련회 조원",
                "verbose_name_plural": "수련회 조원",
                "ordering": ["group", "sort_order", "name", "id"],
            },
        ),
        migrations.CreateModel(
            name="RetreatGroupMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("leader", "조장"), ("vice_leader", "부조장")],
                        default="leader",
                        max_length=20,
                        verbose_name="역할",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="retreat.retreatgroup",
                        verbose_name="조",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retreat_group_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "조 운영진",
                "verbose_name_plural": "조 운영진",
                "ordering": ["group", "role", "user"],
            },
        ),
        migrations.CreateModel(
            name="RetreatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="세션명")),
                (
                    "occurs_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="진행 일시"
                    ),
                ),
                (
                    "sequence",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="occurs_at 미지정 시 정렬 기준.",
                        verbose_name="순서",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="장소"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="retreat.retreatevent",
                        verbose_name="행사",
                    ),
                ),
            ],
            options={
                "verbose_name": "수련회 세션",
                "verbose_name_plural": "수련회 세션",
                "ordering": ["event", "sequence", "occurs_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="RetreatAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "참석"),
                            ("absent", "결석"),
                            ("late", "지각"),
                            ("excused", "사유"),
                        ],
                        default="present",
                        max_length=10,
                        verbose_name="상태",
                    ),
                ),
                (
                    "checked_at",
                    models.DateTimeField(auto_now=True, verbose_name="기록 일시"),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="메모"
                    ),
                ),
                (
                    "checked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retreat_attendance_checks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="기록자",
                    ),
                ),
                (
                    "attendee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="retreat.retreatattendee",
                        verbose_name="조원",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="retreat.retreatsession",
                        verbose_name="세션",
                    ),
                ),
            ],
            options={
                "verbose_name": "수련회 출석",
                "verbose_name_plural": "수련회 출석",
                "ordering": ["session", "attendee"],
            },
        ),
        migrations.AddConstraint(
            model_name="retreatgroup",
            constraint=models.UniqueConstraint(
                fields=("event", "region", "division", "name"),
                name="uniq_retreat_group_event_region_division_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="retreatgroupmembership",
            constraint=models.UniqueConstraint(
                fields=("group", "user"),
                name="uniq_retreat_group_membership_group_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="retreatsession",
            constraint=models.UniqueConstraint(
                fields=("event", "name"), name="uniq_retreat_session_event_name"
            ),
        ),
        migrations.AddIndex(
            model_name="retreatattendance",
            index=models.Index(
                fields=["session", "status"], name="idx_retreat_att_session_status"
            ),
        ),
        migrations.AddConstraint(
            model_name="retreatattendance",
            constraint=models.UniqueConstraint(
                fields=("attendee", "session"),
                name="uniq_retreat_attendance_attendee_session",
            ),
        ),
    ]
