# Generated by Django 6.0.3 on 2026-06-02 02:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retreat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="retreatsession",
            options={
                "ordering": ["event", "sequence", "occurs_at", "id"],
                "verbose_name": "수련회 출석부",
                "verbose_name_plural": "수련회 출석부",
            },
        ),
        migrations.AddField(
            model_name="retreatsession",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="생성 일시",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="retreatsession",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="retreat_sessions_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="생성자",
            ),
        ),
        migrations.AlterField(
            model_name="retreatsession",
            name="name",
            field=models.CharField(max_length=120, verbose_name="출석부 제목"),
        ),
        migrations.CreateModel(
            name="RetreatChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "생성"),
                            ("update", "수정"),
                            ("delete", "삭제"),
                        ],
                        max_length=10,
                        verbose_name="동작",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("session", "출석부"),
                            ("attendee", "조원"),
                            ("attendance", "출석"),
                            ("group_membership", "조 운영진"),
                            ("group", "조"),
                        ],
                        max_length=30,
                        verbose_name="대상 유형",
                    ),
                ),
                ("target_id", models.PositiveIntegerField(verbose_name="대상 ID")),
                (
                    "payload_before",
                    models.JSONField(blank=True, null=True, verbose_name="변경 전"),
                ),
                (
                    "payload_after",
                    models.JSONField(blank=True, null=True, verbose_name="변경 후"),
                ),
                (
                    "changed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="변경 일시"),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retreat_change_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="변경자",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_logs",
                        to="retreat.retreatevent",
                        verbose_name="행사",
                    ),
                ),
            ],
            options={
                "verbose_name": "수련회 변경 이력",
                "verbose_name_plural": "수련회 변경 이력",
                "ordering": ["-changed_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["event", "-changed_at"],
                        name="idx_retreat_changelog_event_at",
                    ),
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="idx_retreat_changelog_target",
                    ),
                ],
            },
        ),
    ]
