# Generated by Django 6.0.3 on 2026-06-02 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retreat", "0002_alter_retreatsession_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RetreatCouncilMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("chairperson", "회장"),
                            ("vice_chairperson", "부회장"),
                            ("secretary", "총무"),
                            ("member", "임원"),
                        ],
                        default="member",
                        max_length=20,
                        verbose_name="역할",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="메모"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retreat_council_memberships_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="등록자",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="council_memberships",
                        to="retreat.retreatevent",
                        verbose_name="행사",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retreat_council_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "수련회 회장단",
                "verbose_name_plural": "수련회 회장단",
                "ordering": ["event", "role", "user"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "user"), name="uniq_retreat_council_event_user"
                    )
                ],
            },
        ),
    ]
