# Generated by Django 6.0.3 on 2026-06-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retreat", "0004_backfill_group_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="retreatattendee",
            options={
                "ordering": ["group", "check_in_status", "sort_order", "name", "id"],
                "verbose_name": "수련회 조원",
                "verbose_name_plural": "수련회 조원",
            },
        ),
        migrations.AddField(
            model_name="retreatattendee",
            name="check_in_status",
            field=models.CharField(
                choices=[("checked_in", "입실"), ("checked_out", "퇴실")],
                default="checked_in",
                help_text="퇴실 상태인 조원은 출석부에서 결석이 기본으로 선택됩니다.",
                max_length=15,
                verbose_name="입·퇴실",
            ),
        ),
        migrations.AlterField(
            model_name="retreatattendance",
            name="status",
            field=models.CharField(
                choices=[("present", "참석"), ("absent", "결석")],
                default="present",
                max_length=10,
                verbose_name="상태",
            ),
        ),
    ]
