# Generated by Django 6.0.3 on 2026-06-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retreat", "0010_attendance_options_changelog_target"),
    ]

    operations = [
        migrations.AddField(
            model_name="retreatattendee",
            name="checked_in_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="입실 시각"),
        ),
        migrations.AddField(
            model_name="retreatattendee",
            name="checked_out_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="퇴실 시각"),
        ),
    ]
