# Generated by Django 6.0.3 on 2026-06-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retreat", "0014_lodging_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="retreatattendee",
            name="expected_check_in_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="예상 입실 시각"
            ),
        ),
        migrations.AddField(
            model_name="retreatattendee",
            name="expected_check_out_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="예상 퇴실 시각"
            ),
        ),
        migrations.AlterField(
            model_name="retreatattendee",
            name="checked_in_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="실제 입실 시각"
            ),
        ),
        migrations.AlterField(
            model_name="retreatattendee",
            name="checked_out_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="실제 퇴실 시각"
            ),
        ),
    ]
