# Generated by Django 6.0.3 on 2026-06-02 14:52

import django.db.models.deletion
from django.db import migrations, models


def backfill_room_region(apps, schema_editor):
    """기존 호실의 region 을 부모 lodging.region 으로 채워 두 가지 기능을 유지한다.

    - 마이그레이션 직후 운영진이 호실별 region/division 을 다시 지정하기 전까지는
      기존 동작(`lodging.region` 매칭)이 그대로 유지되어야 하므로, 호실의
      region 을 lodging.region 으로 백필한다.
    - division 은 비워둔다 (= 미배정). 운영진이 호실 모달에서 지정해야 함.
    """

    LodgingRoom = apps.get_model("retreat", "LodgingRoom")
    rooms_to_update = []
    for room in LodgingRoom.objects.select_related("lodging").all():
        if room.region_id is None and room.lodging.region_id is not None:
            room.region_id = room.lodging.region_id
            rooms_to_update.append(room)
    if rooms_to_update:
        LodgingRoom.objects.bulk_update(rooms_to_update, ["region"])


class Migration(migrations.Migration):

    dependencies = [
        ("retreat", "0015_attendee_expected_stamps"),
        ("users", "0010_userprofile_requested_retreat_event_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lodgingroom",
            name="division",
            field=models.ForeignKey(
                blank=True,
                help_text="비워두면 어느 조에도 노출되지 않습니다 (미배정).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="retreat_lodging_rooms",
                to="users.division",
                verbose_name="부서",
            ),
        ),
        migrations.AddField(
            model_name="lodgingroom",
            name="region",
            field=models.ForeignKey(
                blank=True,
                help_text="비워두면 어느 조에도 노출되지 않습니다 (미배정).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="retreat_lodging_rooms",
                to="users.region",
                verbose_name="지역",
            ),
        ),
        migrations.RunPython(backfill_room_region, migrations.RunPython.noop),
    ]
