# Generated by Django 6.0.3 on 2026-06-03 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retreat", "0016_lodging_room_region_division"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="retreatattendee",
            name="member_role",
            field=models.CharField(
                choices=[
                    ("member", "조원"),
                    ("leader", "조장"),
                    ("vice_leader", "부조장"),
                ],
                default="member",
                max_length=20,
                verbose_name="조 내 역할",
            ),
        ),
        migrations.AddField(
            model_name="retreatattendee",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="retreat_attendee_rows",
                to=settings.AUTH_USER_MODEL,
                verbose_name="연결 계정",
            ),
        ),
    ]
