# Generated by Django 6.0.3 on 2026-06-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retreat", "0017_profile_real_name_attendee_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="retreatsessionattendee",
            name="member_role",
            field=models.CharField(
                choices=[
                    ("member", "조원"),
                    ("leader", "조장"),
                    ("vice_leader", "부조장"),
                ],
                default="member",
                max_length=15,
                verbose_name="구분",
            ),
        ),
    ]
