# Generated by Django 6.0.3 on 2026-06-03 09:10

from django.db import migrations, models


def backfill_mixed_to_unknown(apps, schema_editor):
    LodgingRoom = apps.get_model("retreat", "LodgingRoom")
    LodgingRoom.objects.filter(recommended_gender="mixed").update(
        recommended_gender=""
    )


class Migration(migrations.Migration):

    dependencies = [
        ("retreat", "0018_enrollment_member_role"),
    ]

    operations = [
        migrations.RunPython(
            backfill_mixed_to_unknown, migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="lodgingroom",
            name="recommended_gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "남성"), ("female", "여성"), ("", "미지정")],
                default="",
                max_length=10,
                verbose_name="권장 성별",
            ),
        ),
    ]
