# Generated by Django 6.0.3 on 2026-06-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retreat", "0020_periodic_auto_check_in"),
        ("users", "0012_preserve_profile_on_user_delete"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="retreatgroup",
            name="uniq_retreat_group_event_region_division_name",
        ),
        migrations.AddConstraint(
            model_name="retreatgroup",
            constraint=models.UniqueConstraint(
                fields=("event", "name"), name="uniq_retreat_group_event_name"
            ),
        ),
    ]
