# Generated by Django 6.0.3 on 2026-06-08 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "retreat",
            "0021_remove_retreatgroup_uniq_retreat_group_event_region_division_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="retreatgroup",
            options={
                "ordering": ["event", "order", "id"],
                "verbose_name": "수련회 조",
                "verbose_name_plural": "수련회 조",
            },
        ),
    ]
