# Generated by Django 6.0.3 on 2026-06-08 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retreat", "0022_alter_retreatgroup_ordering"),
        ("users", "0012_preserve_profile_on_user_delete"),
    ]

    operations = [
        migrations.CreateModel(
            name="RetreatGroupScope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retreat_group_extra_scopes",
                        to="users.division",
                        verbose_name="부서",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_scopes",
                        to="retreat.retreatgroup",
                        verbose_name="조",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retreat_group_extra_scopes",
                        to="users.region",
                        verbose_name="지역",
                    ),
                ),
            ],
            options={
                "verbose_name": "수련회 조 보조 범위",
                "verbose_name_plural": "수련회 조 보조 범위",
                "ordering": [
                    "group",
                    "region__sort_order",
                    "division__sort_order",
                    "id",
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("group", "region", "division"),
                        name="uniq_retreat_group_scope_group_region_division",
                    )
                ],
            },
        ),
    ]
