# Generated by Django 6.0.3 on 2026-06-08 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retreat", "0023_retreatgroupscope"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="retreatchangelog",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("session", "출석부"),
                    ("attendee", "조원"),
                    ("enrollment", "출석부 조원"),
                    ("attendance", "출석"),
                    ("group_membership", "조 운영진"),
                    ("group", "조"),
                    ("pickup", "픽업"),
                ],
                max_length=30,
                verbose_name="대상 유형",
            ),
        ),
        migrations.CreateModel(
            name="RetreatPickup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("arrival", "입회"), ("departure", "출회")],
                        db_index=True,
                        max_length=16,
                        verbose_name="구분",
                    ),
                ),
                ("number", models.PositiveIntegerField(verbose_name="번호")),
                ("name", models.CharField(max_length=60, verbose_name="이름")),
                (
                    "train_time",
                    models.CharField(max_length=40, verbose_name="열차 타는 시각"),
                ),
                (
                    "boarding_place",
                    models.CharField(max_length=120, verbose_name="탑승장소"),
                ),
                ("contact", models.CharField(max_length=30, verbose_name="연락처")),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="기타 참고사항",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retreat_pickups_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="등록자",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pickups",
                        to="retreat.retreatevent",
                        verbose_name="행사",
                    ),
                ),
            ],
            options={
                "verbose_name": "수련회 픽업",
                "verbose_name_plural": "수련회 픽업",
                "ordering": ["event", "direction", "number", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "direction", "number"),
                        name="uniq_retreat_pickup_event_direction_number",
                    )
                ],
            },
        ),
    ]
