# Generated by Django 6.0.3 on 2026-06-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retreat", "0024_retreat_pickup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retreatpickup",
            name="train_time",
            field=models.DateTimeField(verbose_name="열차 시각"),
        ),
    ]
