# Generated by Django 6.0.3 on 2026-06-08 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retreat", "0025_alter_retreatpickup_train_time"),
        ("users", "0013_user_signup_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="retreatpickup",
            name="division",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="retreat_pickups",
                to="users.division",
                verbose_name="부서",
            ),
        ),
        migrations.AddField(
            model_name="retreatpickup",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="retreat_pickups",
                to="users.region",
                verbose_name="지역",
            ),
        ),
    ]
