# Generated by Django 6.0.3 on 2026-06-08 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retreat", "0026_retreatpickup_division_retreatpickup_region"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="retreatpickup",
            name="applicant_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="등록 시점의 신청자 이름 스냅샷",
                max_length=60,
                verbose_name="신청자",
            ),
        ),
        migrations.AddField(
            model_name="retreatpickup",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pickups",
                to="retreat.retreatgroup",
                verbose_name="조",
            ),
        ),
        migrations.AlterField(
            model_name="retreatpickup",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="retreat_pickups_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="신청자 계정",
            ),
        ),
    ]
