# Generated by Django 6.0.3 on 2026-06-09 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retreat", "0027_retreatpickup_applicant_name_retreatpickup_group_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="retreatchangelog",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("session", "출석부"),
                    ("attendee", "조원"),
                    ("enrollment", "출석부 조원"),
                    ("attendance", "출석"),
                    ("group_membership", "조 운영진"),
                    ("group", "조"),
                    ("pickup", "픽업"),
                    ("timetable", "타임테이블"),
                ],
                max_length=30,
                verbose_name="대상 유형",
            ),
        ),
        migrations.CreateModel(
            name="RetreatTimetableEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(verbose_name="일자")),
                ("start_time", models.TimeField(verbose_name="시작 시각")),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="종료 시각"),
                ),
                ("title", models.CharField(max_length=120, verbose_name="프로그램명")),
                (
                    "location",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="장소"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="설명"),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="같은 일자·시작 시각일 때 정렬 기준.",
                        verbose_name="정렬",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retreat_timetable_entries_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="등록자",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_entries",
                        to="retreat.retreatevent",
                        verbose_name="행사",
                    ),
                ),
            ],
            options={
                "verbose_name": "수련회 타임테이블",
                "verbose_name_plural": "수련회 타임테이블",
                "ordering": ["day", "start_time", "sort_order", "id"],
                "indexes": [
                    models.Index(
                        fields=["event", "day", "start_time"],
                        name="idx_rt_timetable_event_day",
                    )
                ],
            },
        ),
    ]
