# Generated by Django 6.0.3 on 2026-06-13 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retreat", "0028_alter_retreatchangelog_target_type_and_more"),
        ("users", "0014_user_retired_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="retreatchangelog",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("session", "출석부"),
                    ("attendee", "조원"),
                    ("enrollment", "출석부 조원"),
                    ("attendance", "출석"),
                    ("group_membership", "조 운영진"),
                    ("group", "조"),
                    ("pickup", "픽업"),
                    ("pickup_location", "탑승장소"),
                    ("timetable", "타임테이블"),
                ],
                max_length=30,
                verbose_name="대상 유형",
            ),
        ),
        migrations.CreateModel(
            name="RetreatPickupLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="탑승장소")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="정렬"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retreat_pickup_locations_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="등록자",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pickup_locations",
                        to="retreat.retreatevent",
                        verbose_name="행사",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retreat_pickup_locations",
                        to="users.region",
                        verbose_name="지역",
                    ),
                ),
            ],
            options={
                "verbose_name": "수련회 탑승장소",
                "verbose_name_plural": "수련회 탑승장소",
                "ordering": ["region__sort_order", "sort_order", "name", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "region", "name"),
                        name="uniq_retreat_pickup_location_event_region_name",
                    )
                ],
            },
        ),
    ]
