# Generated by Django 6.0.3 on 2026-06-13 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retreat", "0029_pickup_location"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="retreatpickuplocation",
            options={
                "ordering": ["sort_order", "name", "id"],
                "verbose_name": "수련회 탑승장소",
                "verbose_name_plural": "수련회 탑승장소",
            },
        ),
        migrations.RemoveConstraint(
            model_name="retreatpickuplocation",
            name="uniq_retreat_pickup_location_event_region_name",
        ),
        migrations.AddConstraint(
            model_name="retreatpickuplocation",
            constraint=models.UniqueConstraint(
                fields=("event", "name"), name="uniq_retreat_pickup_location_event_name"
            ),
        ),
        migrations.RemoveField(
            model_name="retreatpickuplocation",
            name="region",
        ),
    ]
