# Generated by Django 6.0.3 on 2026-06-17 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retreat", "0031_retreatattendee_created_by_retreatgroup_created_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="retreatevent",
            options={
                "ordering": ["-start_date", "-id"],
                "verbose_name": "수련회 집회",
                "verbose_name_plural": "수련회 집회",
            },
        ),
        migrations.AlterField(
            model_name="lodging",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lodgings",
                to="retreat.retreatevent",
                verbose_name="집회",
            ),
        ),
        migrations.AlterField(
            model_name="retreatchangelog",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="change_logs",
                to="retreat.retreatevent",
                verbose_name="집회",
            ),
        ),
        migrations.AlterField(
            model_name="retreatcouncilmembership",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="council_memberships",
                to="retreat.retreatevent",
                verbose_name="집회",
            ),
        ),
        migrations.AlterField(
            model_name="retreatevent",
            name="name",
            field=models.CharField(max_length=120, verbose_name="집회명"),
        ),
        migrations.AlterField(
            model_name="retreatgroup",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                to="retreat.retreatevent",
                verbose_name="집회",
            ),
        ),
        migrations.AlterField(
            model_name="retreatpickup",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pickups",
                to="retreat.retreatevent",
                verbose_name="집회",
            ),
        ),
        migrations.AlterField(
            model_name="retreatpickuplocation",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pickup_locations",
                to="retreat.retreatevent",
                verbose_name="집회",
            ),
        ),
        migrations.AlterField(
            model_name="retreatsession",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="retreat.retreatevent",
                verbose_name="집회",
            ),
        ),
        migrations.AlterField(
            model_name="retreattimetableentry",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetable_entries",
                to="retreat.retreatevent",
                verbose_name="집회",
            ),
        ),
    ]
