# Generated by Django 6.0.3 on 2026-06-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retreat", "0034_retreatattendee_participation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="retreatevent",
            name="require_retreat_participation_on_signup",
            field=models.BooleanField(
                default=False,
                help_text="활성 집회에 이 옵션이 켜져 있으면 가입신청서에서 수련회 참석 여부를 반드시 선택해야 합니다.",
                verbose_name="가입신청 시 수련회 참석 여부 필수",
            ),
        ),
    ]
