# Generated by Django 6.0.3 on 2026-06-28 16:36

from django.db import migrations, models


def _resolve_lodging_stay_status(attendee):
    if attendee.participation_status == "absent":
        return "absent"
    if attendee.check_in_status == "checked_out":
        return "ended"
    if attendee.expected_check_in_at is None:
        return "no_stay"
    if attendee.lodging_room_id:
        return "active"
    return "unassigned"


def backfill_lodging_stay_status(apps, schema_editor):
    RetreatAttendee = apps.get_model("retreat", "RetreatAttendee")
    batch = []
    for attendee in RetreatAttendee.objects.iterator(chunk_size=500):
        status = _resolve_lodging_stay_status(attendee)
        if attendee.lodging_stay_status != status:
            attendee.lodging_stay_status = status
            batch.append(attendee)
        if len(batch) >= 500:
            RetreatAttendee.objects.bulk_update(batch, ["lodging_stay_status"])
            batch = []
    if batch:
        RetreatAttendee.objects.bulk_update(batch, ["lodging_stay_status"])


class Migration(migrations.Migration):

    dependencies = [
        ("retreat", "0035_retreatevent_require_signup_retreat_participation"),
    ]

    operations = [
        migrations.AddField(
            model_name="retreatattendee",
            name="lodging_stay_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("active", "숙박 중"),
                    ("unassigned", "미배정"),
                    ("ended", "숙박 종료"),
                    ("no_stay", "숙박 없음"),
                    ("absent", "불참"),
                ],
                max_length=20,
                null=True,
                verbose_name="숙박 상태",
            ),
        ),
        migrations.RunPython(backfill_lodging_stay_status, migrations.RunPython.noop),
    ]
