# Generated by Django 6.0.3 on 2026-07-02 03:35

import django.db.models.deletion
from django.db import migrations, models

_LEGACY_STAFF_ROLES = ("chairperson", "vice_chairperson", "secretary", "member")


def migrate_legacy_council_roles(apps, schema_editor):
    Membership = apps.get_model("retreat", "RetreatCouncilMembership")
    Membership.objects.filter(role__in=_LEGACY_STAFF_ROLES).update(role="event_admin")


class Migration(migrations.Migration):

    dependencies = [
        ("retreat", "0036_attendee_lodging_stay_status"),
        ("users", "0018_userprofile_requested_applicant_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="retreatcouncilmembership",
            options={
                "ordering": ["event", "role", "user"],
                "verbose_name": "집회 운영진",
                "verbose_name_plural": "집회 운영진",
            },
        ),
        migrations.AddField(
            model_name="retreatcouncilmembership",
            name="division",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="retreat_staff_memberships",
                to="users.division",
                verbose_name="담당 부서",
            ),
        ),
        migrations.AddField(
            model_name="retreatcouncilmembership",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="retreat_staff_memberships",
                to="users.region",
                verbose_name="담당 지역",
            ),
        ),
        migrations.RunPython(migrate_legacy_council_roles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="retreatcouncilmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("event_admin", "집회 전체 관리자"),
                    ("event_observer", "집회 전체 관찰자"),
                    ("region_admin", "지역 관리자"),
                    ("region_observer", "지역 관찰자"),
                    ("division_admin", "부서 관리자"),
                    ("division_observer", "부서 관찰자"),
                    ("pickup_observer", "픽업 담당 관찰자"),
                ],
                default="event_admin",
                max_length=32,
                verbose_name="역할",
            ),
        ),
    ]
