# Generated by Django 6.0.3 on 2026-07-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retreat", "0037_staff_rbac_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="retreatattendee",
            name="account_retired_at",
            field=models.DateTimeField(
                blank=True,
                help_text="연결 계정 탈퇴로 숨김 처리된 조원. 슈퍼유저만 조회 가능.",
                null=True,
                verbose_name="계정 탈퇴 일시",
            ),
        ),
        migrations.AddField(
            model_name="retreatpickup",
            name="account_retired_at",
            field=models.DateTimeField(
                blank=True,
                help_text="연결 조원 계정 탈퇴로 숨김 처리된 픽업. 슈퍼유저만 조회 가능.",
                null=True,
                verbose_name="계정 탈퇴 일시",
            ),
        ),
    ]
