# Generated by Django 6.0.3 on 2026-07-02 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retreat", "0038_attendee_pickup_account_retired_at"),
        ("users", "0018_userprofile_requested_applicant_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="retreatevent",
            name="staff_applications_open",
            field=models.BooleanField(
                default=False,
                help_text="켜져 있으면 승인 완료 사용자가 운영진 참가 신청을 제출할 수 있습니다.",
                verbose_name="운영진 모집 중",
            ),
        ),
        migrations.CreateModel(
            name="RetreatStaffApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_role",
                    models.CharField(
                        blank=True,
                        choices=[("leader", "조장"), ("vice_leader", "부조장")],
                        default="",
                        max_length=20,
                        verbose_name="조 역할",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "검토 중"),
                            ("approved", "승인"),
                            ("rejected", "반려"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="상태",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="메모"
                    ),
                ),
                (
                    "rejection_reason",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="반려 사유"
                    ),
                ),
                (
                    "approved_council_role",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=32,
                        verbose_name="승인 council 역할",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="검토 일시"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retreat_staff_applications",
                        to="users.division",
                        verbose_name="부서",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_applications",
                        to="retreat.retreatevent",
                        verbose_name="집회",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_applications",
                        to="retreat.retreatgroup",
                        verbose_name="조",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retreat_staff_applications",
                        to="users.region",
                        verbose_name="지역",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retreat_staff_applications_reviewed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="검토자",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retreat_staff_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="신청자",
                    ),
                ),
            ],
            options={
                "verbose_name": "운영진 참가 신청",
                "verbose_name_plural": "운영진 참가 신청",
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["pending", "approved"])),
                        fields=("event", "user"),
                        name="uniq_retreat_staff_app_event_user_active",
                    )
                ],
            },
        ),
    ]
