# Generated by Django 6.0.3 on 2026-07-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retreat", "0040_staff_application_track"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retreatattendee",
            name="account_retired_at",
            field=models.DateTimeField(
                blank=True,
                help_text="연결 계정 탈퇴로 숨김 처리된 조원.",
                null=True,
                verbose_name="계정 탈퇴 일시",
            ),
        ),
        migrations.AlterField(
            model_name="retreatpickup",
            name="account_retired_at",
            field=models.DateTimeField(
                blank=True,
                help_text="연결 조원 계정 탈퇴로 숨김 처리된 픽업.",
                null=True,
                verbose_name="계정 탈퇴 일시",
            ),
        ),
        migrations.AlterField(
            model_name="retreatstaffapplication",
            name="application_track",
            field=models.CharField(
                blank=True,
                choices=[("council", "집회 운영진"), ("group_leadership", "조 운영진")],
                default="",
                max_length=24,
                verbose_name="신청 유형",
            ),
        ),
    ]
