# Generated by Django 6.0.3 on 2026-07-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retreat", "0041_alter_retreatattendee_account_retired_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retreatattendee",
            name="member_role",
            field=models.CharField(
                choices=[
                    ("member", "조원"),
                    ("leader", "조장"),
                    ("vice_leader", "부조장"),
                    ("teacher", "선생님"),
                ],
                default="member",
                max_length=20,
                verbose_name="조 내 역할",
            ),
        ),
        migrations.AlterField(
            model_name="retreatgroupmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("leader", "조장"),
                    ("vice_leader", "부조장"),
                    ("teacher", "선생님"),
                ],
                default="leader",
                max_length=20,
                verbose_name="역할",
            ),
        ),
        migrations.AlterField(
            model_name="retreatsessionattendee",
            name="member_role",
            field=models.CharField(
                choices=[
                    ("member", "조원"),
                    ("leader", "조장"),
                    ("vice_leader", "부조장"),
                    ("teacher", "선생님"),
                ],
                default="member",
                max_length=15,
                verbose_name="구분",
            ),
        ),
        migrations.AlterField(
            model_name="retreatstaffapplication",
            name="group_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("leader", "조장"),
                    ("vice_leader", "부조장"),
                    ("teacher", "선생님"),
                ],
                default="",
                max_length=20,
                verbose_name="조 역할",
            ),
        ),
    ]
