# Generated by Django 6.0.3 on 2026-07-24 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retreat", "0042_attendee_group_teacher_role"),
        ("users", "0019_userprofile_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="RetreatTravelPreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("arrival", "입실"), ("departure", "퇴실")],
                        db_index=True,
                        max_length=16,
                        verbose_name="구분",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="예: advance, main, late, own_car, bus, bus_after_evening",
                        max_length=40,
                        verbose_name="코드",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="엑셀·UI 문구. 예: 7/30 본진, 8/1 버스",
                        max_length=80,
                        verbose_name="표시명",
                    ),
                ),
                (
                    "occurs_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="버스·본진 등 고정 시각. 자차(수동)는 비워 두고 조원이 달력에서 직접 고름.",
                        null=True,
                        verbose_name="예정 시각",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="정렬"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="사용")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "divisions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="비우면 모든 부서에 노출. 지정 시 해당 부서 조에만 노출.",
                        related_name="retreat_travel_presets",
                        to="users.division",
                        verbose_name="적용 부서",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_presets",
                        to="retreat.retreatevent",
                        verbose_name="집회",
                    ),
                ),
            ],
            options={
                "verbose_name": "수련회 입퇴실 차량 프리셋",
                "verbose_name_plural": "수련회 입퇴실 차량 프리셋",
                "ordering": ["direction", "sort_order", "id"],
                "indexes": [
                    models.Index(
                        fields=["event", "direction", "is_active"],
                        name="idx_rt_travel_preset_event",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "direction", "code"),
                        name="uniq_rt_travel_preset_event_dir_code",
                    )
                ],
            },
        ),
    ]
