# Generated by Django 6.0.3 on 2026-07-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retreat", "0043_travel_preset"),
    ]

    operations = [
        migrations.AddField(
            model_name="retreatattendee",
            name="arrival_travel_is_custom",
            field=models.BooleanField(
                blank=True,
                help_text="True면 웨이브 시각과 같아도 자차로 분류. NULL은 시각 자동매칭.",
                null=True,
                verbose_name="입실 자차(수동)",
            ),
        ),
        migrations.AddField(
            model_name="retreatattendee",
            name="departure_travel_is_custom",
            field=models.BooleanField(
                blank=True,
                help_text="True면 웨이브 시각과 같아도 자차로 분류. NULL은 시각 자동매칭.",
                null=True,
                verbose_name="퇴실 자차(수동)",
            ),
        ),
    ]
