# Generated by Django 6.0.3 on 2026-03-25 04:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CounselingSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="날짜")),
                ("start_time", models.TimeField(verbose_name="시작")),
                ("end_time", models.TimeField(verbose_name="종료")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("open", "예약 가능"),
                            ("pending", "신청 대기"),
                            ("booked", "확정"),
                            ("blocked", "차단"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=16,
                        verbose_name="상태",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "counselor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counseling_slots",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="상담사",
                    ),
                ),
            ],
            options={
                "verbose_name": "상담 슬롯",
                "verbose_name_plural": "상담 슬롯",
            },
        ),
        migrations.CreateModel(
            name="CounselingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="공개 ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("accepted", "수락"),
                            ("rejected", "거절"),
                            ("cancelled", "취소"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                        verbose_name="상태",
                    ),
                ),
                (
                    "applicant_message",
                    models.TextField(blank=True, verbose_name="상담 요청 내용"),
                ),
                (
                    "counselor_notes_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="상담 메모(리치 텍스트/Quill delta 등)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counseling_requests_sent",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="신청자",
                    ),
                ),
                (
                    "counselor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counseling_requests_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="상담사",
                    ),
                ),
                (
                    "slot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="counseling_request",
                        to="counseling.counselingslot",
                        verbose_name="슬롯",
                    ),
                ),
            ],
            options={
                "verbose_name": "상담 신청",
                "verbose_name_plural": "상담 신청",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CounselorDayOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="날짜")),
                (
                    "is_closed",
                    models.BooleanField(
                        default=False, verbose_name="휴무(해당 일 전체)"
                    ),
                ),
                (
                    "custom_slots_json",
                    models.JSONField(
                        blank=True,
                        help_text='시작 시 정수 리스트 예: [10,11,12] 또는 [["10:00","11:00"], ...]',
                        null=True,
                        verbose_name="커스텀 슬롯",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "counselor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counselor_day_overrides",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="상담사",
                    ),
                ),
            ],
            options={
                "verbose_name": "상담사 일별 예약 오버라이드",
                "verbose_name_plural": "상담사 일별 예약 오버라이드",
            },
        ),
        migrations.CreateModel(
            name="CounselorScheduleSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slot_duration_minutes",
                    models.PositiveSmallIntegerField(
                        default=60, verbose_name="슬롯 길이(분)"
                    ),
                ),
                (
                    "default_start_hour",
                    models.PositiveSmallIntegerField(
                        default=10, verbose_name="기본 시작 시"
                    ),
                ),
                (
                    "default_end_hour",
                    models.PositiveSmallIntegerField(
                        default=23,
                        help_text="예: 23이면 22:00~23:00 슬롯까지 생성",
                        verbose_name="기본 종료 시(마지막 슬롯이 이 시각에 끝남)",
                    ),
                ),
                (
                    "weekday_hours_json",
                    models.JSONField(
                        blank=True,
                        help_text='예: {"0": {"start": 10, "end": 23}, ...} 월=0',
                        null=True,
                        verbose_name="요일별 시간(선택)",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counselor_schedule_settings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="상담사",
                    ),
                ),
            ],
            options={
                "verbose_name": "상담사 일정 템플릿",
                "verbose_name_plural": "상담사 일정 템플릿",
            },
        ),
        migrations.AddIndex(
            model_name="counselingslot",
            index=models.Index(
                fields=["counselor", "date", "state"],
                name="counseling__counsel_211739_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="counselingslot",
            constraint=models.UniqueConstraint(
                fields=("counselor", "date", "start_time"),
                name="unique_counselor_date_start",
            ),
        ),
        migrations.AddIndex(
            model_name="counselingrequest",
            index=models.Index(
                fields=["counselor", "status"], name="counseling__counsel_21aad3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="counselingrequest",
            index=models.Index(
                fields=["applicant", "status"], name="counseling__applica_f203a0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="counselordayoverride",
            constraint=models.UniqueConstraint(
                fields=("counselor", "date"), name="unique_counselor_day_override"
            ),
        ),
    ]
