version = 5.7.0
archive_dir = /etc/letsencrypt/archive/shalom.dev.api.jcc-seoul.com
cert = /etc/letsencrypt/live/shalom.dev.api.jcc-seoul.com/cert.pem
privkey = /etc/letsencrypt/live/shalom.dev.api.jcc-seoul.com/privkey.pem
chain = /etc/letsencrypt/live/shalom.dev.api.jcc-seoul.com/chain.pem
fullchain = /etc/letsencrypt/live/shalom.dev.api.jcc-seoul.com/fullchain.pem
[renewalparams]
account = 60fcaf50d1d322ccce4eae20654d28c3
rsa_key_size = 2048
key_type = ecdsa
elliptic_curve = secp256r1
pref_challs = dns-01,
server = https://acme-v02.api.letsencrypt.org/directory
authenticator = dns-route53
[acme_renewal_info]
ari_retry_after = 2026-07-22T12:57:51
