# Generated by Django 6.0.3 on 2026-03-14 07:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_ko", models.CharField(max_length=50, verbose_name="직책명")),
                (
                    "code",
                    models.SlugField(
                        help_text="예: president, vice_president, region_leader",
                        max_length=30,
                        unique=True,
                        verbose_name="코드",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("leadership", "회장단"),
                            ("department", "부서"),
                            ("region", "지역"),
                            ("team", "팀"),
                            ("cell", "셀"),
                            ("praise", "찬양단"),
                            ("pastor", "담당 목사"),
                        ],
                        default="department",
                        max_length=20,
                        verbose_name="구분",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="정렬 순서"
                    ),
                ),
            ],
            options={
                "verbose_name": "직책",
                "verbose_name_plural": "직책",
                "ordering": ["sort_order", "name_ko"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("name_ko", models.CharField(max_length=50, verbose_name="한글 이름")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자",
                "verbose_name_plural": "사용자",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_ko", models.CharField(max_length=100, verbose_name="이름")),
                (
                    "code",
                    models.SlugField(
                        help_text="예: newcomer, multimedia, hyunhye_region",
                        unique=True,
                        verbose_name="코드",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("top", "상위(담당 목사 직속)"),
                            ("leadership", "회장단"),
                            ("department", "부서"),
                            ("region", "지역"),
                            ("team", "팀"),
                        ],
                        default="department",
                        max_length=20,
                        verbose_name="구분",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="정렬 순서"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="users.department",
                        verbose_name="상위 부서",
                    ),
                ),
            ],
            options={
                "verbose_name": "부서/지역/팀",
                "verbose_name_plural": "부서/지역/팀",
                "ordering": ["sort_order", "name_ko"],
            },
        ),
        migrations.CreateModel(
            name="MemberRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="정렬 순서"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        help_text="회장단·담당목사 등 부서 없으면 비움",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_roles",
                        to="users.department",
                        verbose_name="소속 부서/지역/팀",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="member_roles",
                        to="users.role",
                        verbose_name="직책",
                    ),
                ),
            ],
            options={
                "verbose_name": "구성원 직책",
                "verbose_name_plural": "구성원 직책",
                "ordering": ["department", "role__sort_order", "sort_order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "role", "department"),
                        name="unique_user_role_department",
                    )
                ],
            },
        ),
    ]
