# Generated by Django 6.0.3 on 2026-03-22 15:56

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import users.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="직책명")),
                (
                    "code",
                    models.SlugField(max_length=30, unique=True, verbose_name="코드"),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="정렬 순서"
                    ),
                ),
            ],
            options={
                "verbose_name": "직책",
                "verbose_name_plural": "직책",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="RoleLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="직급명")),
                (
                    "code",
                    models.SlugField(max_length=30, unique=True, verbose_name="코드"),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="숫자 클수록 상위 권한. 목사=100, 전도사=80, 부장=60, 일반=0",
                        verbose_name="레벨",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="정렬 순서"
                    ),
                ),
            ],
            options={
                "verbose_name": "직급/권한",
                "verbose_name_plural": "직급/권한",
                "ordering": ["-level", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "role_level",
                    models.ForeignKey(
                        blank=True,
                        help_text="목사/전도사/부장 등 → Admin·API 노출 범위",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="users.rolelevel",
                        verbose_name="직급/권한",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자(계정)",
                "verbose_name_plural": "사용자(계정)",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="이름")),
                ("code", models.SlugField(unique=True, verbose_name="코드")),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="정렬 순서"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="users.division",
                        verbose_name="상위 부서",
                    ),
                ),
            ],
            options={
                "verbose_name": "상위 부서",
                "verbose_name_plural": "상위 부서",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="이름")),
                ("code", models.SlugField(unique=True, verbose_name="코드")),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="정렬 순서"
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clubs",
                        to="users.division",
                        verbose_name="소속 부서",
                    ),
                ),
            ],
            options={
                "verbose_name": "동아리",
                "verbose_name_plural": "동아리",
                "ordering": ["division", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceWeek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "week_sunday",
                    models.DateField(
                        help_text="이 출석 주차를 식별하는 주일 날짜(해당 주의 주일).",
                        verbose_name="기준 주일",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="비고"
                    ),
                ),
                (
                    "auto_created",
                    models.BooleanField(
                        default=False,
                        help_text="ensure_weekly_attendance_weeks 등으로 생성된 경우 True",
                        verbose_name="자동 생성됨",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최초 등록자",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최종 수정자",
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_weeks",
                        to="users.division",
                        verbose_name="부서",
                    ),
                ),
            ],
            options={
                "verbose_name": "주간 출석(주차)",
                "verbose_name_plural": "주간 출석(주차)",
                "ordering": ["-week_sunday", "division"],
            },
        ),
        migrations.CreateModel(
            name="FunctionalDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="이름")),
                ("code", models.SlugField(unique=True, verbose_name="코드")),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="정렬 순서"
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="functional_departments",
                        to="users.division",
                        verbose_name="소속 부서",
                    ),
                ),
            ],
            options={
                "verbose_name": "일하는 부서",
                "verbose_name_plural": "일하는 부서",
                "ordering": ["division", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="이름")),
                (
                    "name_alias",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="별칭·통칭"
                    ),
                ),
                (
                    "import_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="엑셀 등 병합용",
                        max_length=64,
                        verbose_name="임포트 키",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최초 등록자",
                    ),
                ),
                (
                    "linked_user",
                    models.OneToOneField(
                        blank=True,
                        help_text="회원가입 후 교적과 연결할 때만 사용",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_member_record",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="연결된 앱 계정",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최종 수정자",
                    ),
                ),
            ],
            options={
                "verbose_name": "교적(멤버)",
                "verbose_name_plural": "교적(멤버)",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MemberClub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="정렬 순서"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_club_memberships",
                        to="users.club",
                        verbose_name="동아리",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_clubs",
                        to="users.member",
                        verbose_name="멤버(교적)",
                    ),
                ),
            ],
            options={
                "verbose_name": "교적 동아리 소속",
                "verbose_name_plural": "교적 동아리 소속",
                "ordering": ["member", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="MemberFamilyMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="이름")),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("father", "부"),
                            ("mother", "모"),
                            ("spouse", "배우자"),
                            ("elder_brother", "형/오빠"),
                            ("younger_brother", "남동생"),
                            ("elder_sister", "언니/누나"),
                            ("younger_sister", "여동생"),
                            ("son", "아들"),
                            ("daughter", "딸"),
                            ("other", "기타"),
                        ],
                        default="other",
                        max_length=30,
                        verbose_name="관계",
                    ),
                ),
                (
                    "relationship_note",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="기타 선택 시 또는 세부 표기",
                        max_length=50,
                        verbose_name="관계(직접입력)",
                    ),
                ),
                (
                    "affiliation_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="예: 광명교구, 청년부, 불신",
                        max_length=100,
                        verbose_name="소속",
                    ),
                ),
                (
                    "church_position",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="직분"
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, default="", verbose_name="비고"),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="정렬 순서"
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        blank=True,
                        help_text="카드 표기와 맞출 때만 연결",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="member_family_affiliations",
                        to="users.division",
                        verbose_name="소속 부서(선택)",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_members",
                        to="users.member",
                        verbose_name="멤버",
                    ),
                ),
            ],
            options={
                "verbose_name": "멤버 가족",
                "verbose_name_plural": "멤버 가족",
                "ordering": ["member", "sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="MemberProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="생년월일"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="교적부용. 앱 프로필 휴대폰과 별개일 수 있음.",
                        max_length=30,
                        validators=[users.validators.validate_korea_mobile_phone],
                        verbose_name="연락처(교적)",
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, default="", verbose_name="주소"),
                ),
                (
                    "church_position_display",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="직분·직책(카드)",
                    ),
                ),
                (
                    "workplace_display",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="직장(업무)",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="members/profile/",
                        verbose_name="사진",
                    ),
                ),
                (
                    "family_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="members/family/",
                        verbose_name="가족 사진",
                    ),
                ),
                (
                    "staff_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="관리자·목회진만 열람",
                        verbose_name="목회 메모",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최초 등록자",
                    ),
                ),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pastoral_profile",
                        to="users.member",
                        verbose_name="멤버(교적)",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최종 수정자",
                    ),
                ),
            ],
            options={
                "verbose_name": "교적 프로필",
                "verbose_name_plural": "교적 프로필",
            },
        ),
        migrations.CreateModel(
            name="MemberVisitLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visit_date",
                    models.DateField(
                        help_text="매주 통화면 해당 주 대표일(예: 통화한 날)",
                        verbose_name="심방일(기준일)",
                    ),
                ),
                (
                    "contact_method",
                    models.CharField(
                        choices=[
                            ("phone", "전화"),
                            ("visit", "방문"),
                            ("other", "기타"),
                        ],
                        default="phone",
                        max_length=20,
                        verbose_name="방식",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="상황, 대화 요약 등", verbose_name="내용"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visit_logs",
                        to="users.member",
                        verbose_name="멤버",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_member_visits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="기록자",
                    ),
                ),
            ],
            options={
                "verbose_name": "멤버 심방 기록",
                "verbose_name_plural": "멤버 심방 기록",
                "ordering": ["-visit_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MidweekAttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("wednesday", "수요일 예배"),
                            ("saturday", "토요일 예배"),
                        ],
                        max_length=20,
                        verbose_name="예배",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("present", "참석"),
                            ("absent", "불참"),
                            ("online", "온라인"),
                        ],
                        help_text="비우면 아직 미입력",
                        max_length=20,
                        null=True,
                        verbose_name="출석",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최초 등록자",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="midweek_attendance_records",
                        to="users.member",
                        verbose_name="멤버",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최종 수정자",
                    ),
                ),
                (
                    "week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="midweek_records",
                        to="users.attendanceweek",
                        verbose_name="주차",
                    ),
                ),
            ],
            options={
                "verbose_name": "수·토 출석",
                "verbose_name_plural": "수·토 출석",
                "ordering": ["week", "service_type", "member__name"],
            },
        ),
        migrations.CreateModel(
            name="MemberFunctionalDeptRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="정렬 순서"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "functional_department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_roles",
                        to="users.functionaldepartment",
                        verbose_name="일하는 부서",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="functional_dept_roles",
                        to="users.member",
                        verbose_name="멤버(교적)",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="member_functional_roles",
                        to="users.role",
                        verbose_name="직책",
                    ),
                ),
            ],
            options={
                "verbose_name": "교적 일하는 부서 직책",
                "verbose_name_plural": "교적 일하는 부서 직책",
                "ordering": ["member", "functional_department", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="팀명")),
                (
                    "code",
                    models.SlugField(
                        help_text="동일 Division 내에서만 유일하면 됨",
                        verbose_name="코드",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="정렬 순서"
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="users.division",
                        verbose_name="소속 부서",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="users.team",
                        verbose_name="상위 팀(예: 셀)",
                    ),
                ),
            ],
            options={
                "verbose_name": "팀",
                "verbose_name_plural": "팀",
                "ordering": ["division", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SundayAttendanceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "venue",
                    models.CharField(
                        choices=[
                            ("incheon", "인천 예배"),
                            ("seoul", "서울 예배"),
                            ("online", "온라인"),
                            ("branch", "지교회"),
                        ],
                        max_length=20,
                        verbose_name="주일 구분",
                    ),
                ),
                (
                    "session_part",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="서울/인천 1~4부. 온라인·지교회는 0.",
                        verbose_name="부",
                    ),
                ),
                (
                    "branch_label",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="지교회 표기",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최초 등록자",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sunday_attendance_lines",
                        to="users.member",
                        verbose_name="멤버",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최종 수정자",
                    ),
                ),
                (
                    "week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sunday_lines",
                        to="users.attendanceweek",
                        verbose_name="주차",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sunday_attendance_lines",
                        to="users.team",
                        verbose_name="팀",
                    ),
                ),
            ],
            options={
                "verbose_name": "주일 출석(행)",
                "verbose_name_plural": "주일 출석(행)",
                "ordering": ["week", "member__name", "venue", "session_part"],
            },
        ),
        migrations.CreateModel(
            name="MemberDivisionTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="주 소속"),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="정렬 순서"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_division_teams",
                        to="users.division",
                        verbose_name="부서",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="division_teams",
                        to="users.member",
                        verbose_name="멤버(교적)",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_division_teams",
                        to="users.team",
                        verbose_name="팀",
                    ),
                ),
            ],
            options={
                "verbose_name": "교적 부서·팀 소속",
                "verbose_name_plural": "교적 부서·팀 소속",
                "ordering": ["member", "-is_primary", "division", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="TeamAttendanceSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_date", models.DateField(verbose_name="날짜")),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="비우면 앱에서 팀명+출석부로 표시",
                        max_length=120,
                        verbose_name="제목",
                    ),
                ),
                (
                    "period_count",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="1교시·2교시 … (최대 20)",
                        verbose_name="교시 수",
                    ),
                ),
                (
                    "period_labels",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='비우면 ["1교시","2교시",…]',
                        verbose_name="교시 라벨",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="메모"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attendance_week",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team_sessions",
                        to="users.attendanceweek",
                        verbose_name="연결 주차(선택)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최초 등록자",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_sessions",
                        to="users.team",
                        verbose_name="팀",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최종 수정자",
                    ),
                ),
            ],
            options={
                "verbose_name": "팀 출석(회차)",
                "verbose_name_plural": "팀 출석(회차)",
                "ordering": ["-session_date", "team"],
            },
        ),
        migrations.CreateModel(
            name="TeamMemberSlotAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slot_index",
                    models.PositiveSmallIntegerField(
                        help_text="1 = 1교시", verbose_name="교시 번호"
                    ),
                ),
                (
                    "picks",
                    models.JSONField(blank=True, default=list, verbose_name="선택(칩)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최초 등록자",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_slot_attendances",
                        to="users.member",
                        verbose_name="멤버(교적)",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slot_rows",
                        to="users.teamattendancesession",
                        verbose_name="팀 출석 회차",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최종 수정자",
                    ),
                ),
            ],
            options={
                "verbose_name": "팀 출석 교시(칩)",
                "verbose_name_plural": "팀 출석 교시(칩)",
                "ordering": ["session", "member__name", "slot_index"],
            },
        ),
        migrations.CreateModel(
            name="UserClub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="정렬 순서"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_memberships",
                        to="users.club",
                        verbose_name="동아리",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clubs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 동아리 소속",
                "verbose_name_plural": "사용자 동아리 소속",
                "ordering": ["user", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="UserDivisionTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="주 소속"),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="정렬 순서"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_division_teams",
                        to="users.division",
                        verbose_name="부서",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_division_teams",
                        to="users.team",
                        verbose_name="팀",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="division_teams",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 부서·팀 소속",
                "verbose_name_plural": "사용자 부서·팀 소속",
                "ordering": ["user", "-is_primary", "division", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="UserFunctionalDeptRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="정렬 순서"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "functional_department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_member_roles",
                        to="users.functionaldepartment",
                        verbose_name="일하는 부서",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_functional_roles",
                        to="users.role",
                        verbose_name="직책",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="functional_dept_roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 일하는 부서 직책",
                "verbose_name_plural": "사용자 일하는 부서 직책",
                "ordering": ["user", "functional_department", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="앱·관리자에 보이는 이름",
                        max_length=50,
                        verbose_name="표시 이름",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=30,
                        validators=[users.validators.validate_korea_mobile_phone],
                        verbose_name="휴대폰",
                    ),
                ),
                (
                    "phone_verified",
                    models.BooleanField(default=False, verbose_name="휴대폰 인증 완료"),
                ),
                (
                    "phone_verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="인증 완료 시각"
                    ),
                ),
                (
                    "phone_otp_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="인증번호 검증용(평문 저장 금지)",
                        max_length=128,
                        verbose_name="OTP 해시(임시)",
                    ),
                ),
                (
                    "phone_otp_expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="OTP 만료"
                    ),
                ),
                (
                    "phone_otp_attempts",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="OTP 시도 횟수"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="users/avatars/",
                        verbose_name="프로필 이미지",
                    ),
                ),
                ("bio", models.TextField(blank=True, default="", verbose_name="소개")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="계정",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 프로필",
                "verbose_name_plural": "사용자 프로필",
            },
        ),
        migrations.CreateModel(
            name="WorshipRosterScope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "venue",
                    models.CharField(
                        choices=[
                            ("incheon", "인천 예배"),
                            ("seoul", "서울 예배"),
                            ("online", "온라인"),
                            ("branch", "지교회"),
                        ],
                        max_length=20,
                        verbose_name="예배 구분",
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        help_text="예: 2024", verbose_name="연도"
                    ),
                ),
                (
                    "session_part",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="1~4부. 인천(미구분 시 기본 3). 온라인/지교회는 0.",
                        verbose_name="부",
                    ),
                ),
                (
                    "branch_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="지교회일 때 하위 폴더명 등 (서울/인천/온라인은 보통 비움)",
                        max_length=100,
                        verbose_name="지교회 표기",
                    ),
                ),
                (
                    "snapshot_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="한 파일에 주차별 시트가 여러 개일 때 구분. 기본 임포트는 비움(단일 시트). --all-sheets 시 시트명이 들어감.",
                        max_length=200,
                        verbose_name="스냅샷(시트) 구분",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="정렬"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최초 등록자",
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worship_roster_scopes",
                        to="users.division",
                        verbose_name="부서",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최종 수정자",
                    ),
                ),
            ],
            options={
                "verbose_name": "출석 명단 구분",
                "verbose_name_plural": "출석 명단 구분",
                "ordering": [
                    "-year",
                    "venue",
                    "session_part",
                    "branch_label",
                    "snapshot_label",
                ],
            },
        ),
        migrations.CreateModel(
            name="WorshipRosterEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_rel_path",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="원본 파일(상대경로)",
                    ),
                ),
                (
                    "sheet_name",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="시트명"
                    ),
                ),
                (
                    "first_imported_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="최초 반영 시각"
                    ),
                ),
                (
                    "last_imported_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="마지막 반영 시각"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최초 등록자",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worship_roster_entries",
                        to="users.member",
                        verbose_name="멤버",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        help_text="엑셀 팀 열 기준",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="worship_roster_entries",
                        to="users.team",
                        verbose_name="팀",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최종 수정자",
                    ),
                ),
                (
                    "scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="users.worshiprosterscope",
                        verbose_name="명단 구분",
                    ),
                ),
            ],
            options={
                "verbose_name": "출석 명단 구성원",
                "verbose_name_plural": "출석 명단 구성원",
                "ordering": ["scope", "member__name"],
            },
        ),
        migrations.AddConstraint(
            model_name="attendanceweek",
            constraint=models.UniqueConstraint(
                fields=("division", "week_sunday"),
                name="uniq_attendance_week_division_sunday",
            ),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(fields=["name"], name="users_membe_name_d53d4b_idx"),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(
                fields=["import_key"], name="users_membe_import__45806c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="memberclub",
            unique_together={("member", "club")},
        ),
        migrations.AddIndex(
            model_name="membervisitlog",
            index=models.Index(
                fields=["member", "-visit_date"], name="users_membe_member__a5dfff_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="midweekattendancerecord",
            constraint=models.UniqueConstraint(
                fields=("week", "member", "service_type"),
                name="uniq_midweek_week_member_service",
            ),
        ),
        migrations.AddConstraint(
            model_name="memberfunctionaldeptrole",
            constraint=models.UniqueConstraint(
                fields=("member", "functional_department", "role"),
                name="unique_member_funcdept_role",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="team",
            unique_together={("division", "code")},
        ),
        migrations.AddConstraint(
            model_name="sundayattendanceline",
            constraint=models.UniqueConstraint(
                fields=("week", "member", "venue", "session_part", "branch_label"),
                name="uniq_sunday_line_week_member_venue_part_branch",
            ),
        ),
        migrations.AddConstraint(
            model_name="memberdivisionteam",
            constraint=models.UniqueConstraint(
                fields=("member", "division", "team"),
                name="unique_member_division_team",
            ),
        ),
        migrations.AddConstraint(
            model_name="teamattendancesession",
            constraint=models.UniqueConstraint(
                fields=("team", "session_date"), name="uniq_team_attendance_team_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="teammemberslotattendance",
            constraint=models.UniqueConstraint(
                fields=("session", "member", "slot_index"),
                name="uniq_team_slot_session_member_index",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userclub",
            unique_together={("user", "club")},
        ),
        migrations.AddConstraint(
            model_name="userdivisionteam",
            constraint=models.UniqueConstraint(
                fields=("user", "division", "team"), name="unique_user_division_team"
            ),
        ),
        migrations.AddConstraint(
            model_name="userfunctionaldeptrole",
            constraint=models.UniqueConstraint(
                fields=("user", "functional_department", "role"),
                name="unique_user_funcdept_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="worshiprosterscope",
            constraint=models.UniqueConstraint(
                fields=(
                    "division",
                    "venue",
                    "year",
                    "session_part",
                    "branch_label",
                    "snapshot_label",
                ),
                name="uniq_worship_roster_scope_div_venue_year_part_branch_snap",
            ),
        ),
        migrations.AddConstraint(
            model_name="worshiprosterentry",
            constraint=models.UniqueConstraint(
                fields=("scope", "member"),
                name="uniq_worship_roster_entry_scope_member",
            ),
        ),
    ]
