# Generated by Django 6.0.3 on 2026-03-22 16:19

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import users.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="직책명")),
                (
                    "code",
                    models.SlugField(max_length=30, unique=True, verbose_name="코드"),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="정렬 순서"
                    ),
                ),
            ],
            options={
                "verbose_name": "직책",
                "verbose_name_plural": "직책",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="RoleLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="직급명")),
                (
                    "code",
                    models.SlugField(max_length=30, unique=True, verbose_name="코드"),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="숫자 클수록 상위 권한. 목사=100, 전도사=80, 부장=60, 일반=0",
                        verbose_name="레벨",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="정렬 순서"
                    ),
                ),
            ],
            options={
                "verbose_name": "직급/권한",
                "verbose_name_plural": "직급/권한",
                "ordering": ["-level", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="이름")),
                ("code", models.SlugField(unique=True, verbose_name="코드")),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="정렬 순서"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="users.division",
                        verbose_name="상위 부서",
                    ),
                ),
            ],
            options={
                "verbose_name": "상위 부서",
                "verbose_name_plural": "상위 부서",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="이름")),
                ("code", models.SlugField(unique=True, verbose_name="코드")),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="정렬 순서"
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clubs",
                        to="users.division",
                        verbose_name="소속 부서",
                    ),
                ),
            ],
            options={
                "verbose_name": "동아리",
                "verbose_name_plural": "동아리",
                "ordering": ["division", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="FunctionalDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="이름")),
                ("code", models.SlugField(unique=True, verbose_name="코드")),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="정렬 순서"
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="functional_departments",
                        to="users.division",
                        verbose_name="소속 부서",
                    ),
                ),
            ],
            options={
                "verbose_name": "일하는 부서",
                "verbose_name_plural": "일하는 부서",
                "ordering": ["division", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "role_level",
                    models.ForeignKey(
                        blank=True,
                        help_text="목사/전도사/부장 등 → Admin·API 노출 범위",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="users.rolelevel",
                        verbose_name="직급/권한",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자(계정)",
                "verbose_name_plural": "사용자(계정)",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="팀명")),
                (
                    "code",
                    models.SlugField(
                        help_text="동일 Division 내에서만 유일하면 됨",
                        verbose_name="코드",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="정렬 순서"
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="users.division",
                        verbose_name="소속 부서",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="users.team",
                        verbose_name="상위 팀(예: 셀)",
                    ),
                ),
            ],
            options={
                "verbose_name": "팀",
                "verbose_name_plural": "팀",
                "ordering": ["division", "sort_order", "name"],
                "unique_together": {("division", "code")},
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="앱·관리자에 보이는 이름",
                        max_length=50,
                        verbose_name="표시 이름",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=30,
                        validators=[users.validators.validate_korea_mobile_phone],
                        verbose_name="휴대폰",
                    ),
                ),
                (
                    "phone_verified",
                    models.BooleanField(default=False, verbose_name="휴대폰 인증 완료"),
                ),
                (
                    "phone_verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="인증 완료 시각"
                    ),
                ),
                (
                    "phone_otp_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="인증번호 검증용(평문 저장 금지)",
                        max_length=128,
                        verbose_name="OTP 해시(임시)",
                    ),
                ),
                (
                    "phone_otp_expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="OTP 만료"
                    ),
                ),
                (
                    "phone_otp_attempts",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="OTP 시도 횟수"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="users/avatars/",
                        verbose_name="프로필 이미지",
                    ),
                ),
                ("bio", models.TextField(blank=True, default="", verbose_name="소개")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="계정",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 프로필",
                "verbose_name_plural": "사용자 프로필",
            },
        ),
        migrations.CreateModel(
            name="UserClub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="정렬 순서"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_memberships",
                        to="users.club",
                        verbose_name="동아리",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clubs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 동아리 소속",
                "verbose_name_plural": "사용자 동아리 소속",
                "ordering": ["user", "sort_order"],
                "unique_together": {("user", "club")},
            },
        ),
        migrations.CreateModel(
            name="UserDivisionTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="주 소속"),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="정렬 순서"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_division_teams",
                        to="users.division",
                        verbose_name="부서",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_division_teams",
                        to="users.team",
                        verbose_name="팀",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="division_teams",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 부서·팀 소속",
                "verbose_name_plural": "사용자 부서·팀 소속",
                "ordering": ["user", "-is_primary", "division", "sort_order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "division", "team"),
                        name="unique_user_division_team",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserFunctionalDeptRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="정렬 순서"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "functional_department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_member_roles",
                        to="users.functionaldepartment",
                        verbose_name="일하는 부서",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_functional_roles",
                        to="users.role",
                        verbose_name="직책",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="functional_dept_roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 일하는 부서 직책",
                "verbose_name_plural": "사용자 일하는 부서 직책",
                "ordering": ["user", "functional_department", "sort_order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "functional_department", "role"),
                        name="unique_user_funcdept_role",
                    )
                ],
            },
        ),
    ]
