# Generated by Django 6.0.3 on 2026-03-14 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_ko", models.CharField(max_length=100, verbose_name="이름")),
                ("code", models.SlugField(unique=True, verbose_name="코드")),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="정렬 순서"
                    ),
                ),
            ],
            options={
                "verbose_name": "동아리",
                "verbose_name_plural": "동아리",
                "ordering": ["division", "sort_order", "name_ko"],
            },
        ),
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_ko", models.CharField(max_length=100, verbose_name="이름")),
                ("code", models.SlugField(unique=True, verbose_name="코드")),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="정렬 순서"
                    ),
                ),
            ],
            options={
                "verbose_name": "상위 부서",
                "verbose_name_plural": "상위 부서",
                "ordering": ["sort_order", "name_ko"],
            },
        ),
        migrations.CreateModel(
            name="FunctionalDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_ko", models.CharField(max_length=100, verbose_name="이름")),
                ("code", models.SlugField(unique=True, verbose_name="코드")),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="정렬 순서"
                    ),
                ),
            ],
            options={
                "verbose_name": "일하는 부서",
                "verbose_name_plural": "일하는 부서",
                "ordering": ["division", "sort_order", "name_ko"],
            },
        ),
        migrations.CreateModel(
            name="RoleLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_ko", models.CharField(max_length=50, verbose_name="직급명")),
                (
                    "code",
                    models.SlugField(max_length=30, unique=True, verbose_name="코드"),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="숫자 클수록 상위 권한. 목사=100, 전도사=80, 부장=60, 일반=0",
                        verbose_name="레벨",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="정렬 순서"
                    ),
                ),
            ],
            options={
                "verbose_name": "직급/권한",
                "verbose_name_plural": "직급/권한",
                "ordering": ["-level", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_ko", models.CharField(max_length=100, verbose_name="팀명")),
                (
                    "code",
                    models.SlugField(
                        help_text="동일 Division 내에서만 유일하면 됨",
                        verbose_name="코드",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="정렬 순서"
                    ),
                ),
            ],
            options={
                "verbose_name": "팀",
                "verbose_name_plural": "팀",
                "ordering": ["division", "sort_order", "name_ko"],
            },
        ),
        migrations.CreateModel(
            name="UserClub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="정렬 순서"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "동아리 소속",
                "verbose_name_plural": "동아리 소속",
                "ordering": ["user", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="UserDivisionTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="이 부서에서의 주 소속 팀(한 부서당 하나 권장)",
                        verbose_name="주 소속",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="정렬 순서"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "부서·팀 소속",
                "verbose_name_plural": "부서·팀 소속",
                "ordering": ["user", "-is_primary", "division", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="UserFunctionalDeptRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="정렬 순서"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "일하는 부서 직책",
                "verbose_name_plural": "일하는 부서 직책",
                "ordering": ["user", "functional_department", "sort_order"],
            },
        ),
        migrations.RemoveField(
            model_name="department",
            name="parent",
        ),
        migrations.RemoveConstraint(
            model_name="memberrole",
            name="unique_user_role_department",
        ),
        migrations.RemoveField(
            model_name="role",
            name="kind",
        ),
        migrations.AlterField(
            model_name="role",
            name="code",
            field=models.SlugField(max_length=30, unique=True, verbose_name="코드"),
        ),
        migrations.AddField(
            model_name="division",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="users.division",
                verbose_name="상위 부서",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="division",
            field=models.ForeignKey(
                blank=True,
                help_text="비우면 교회 전체 동아리",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clubs",
                to="users.division",
                verbose_name="소속 부서",
            ),
        ),
        migrations.AddField(
            model_name="functionaldepartment",
            name="division",
            field=models.ForeignKey(
                blank=True,
                help_text="비우면 교회 전체 부서",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="functional_departments",
                to="users.division",
                verbose_name="소속 부서",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="role_level",
            field=models.ForeignKey(
                blank=True,
                help_text="목사/전도사/부장 등 → 노출 범위(목사님만 보기, 해당 부서만 보기) 결정",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="users.rolelevel",
                verbose_name="직급/권한",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="division",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="users.division",
                verbose_name="소속 부서",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="users.team",
                verbose_name="상위 팀(예: 셀)",
            ),
        ),
        migrations.AddField(
            model_name="userclub",
            name="club",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="users.club",
                verbose_name="동아리",
            ),
        ),
        migrations.AddField(
            model_name="userclub",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clubs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
        migrations.AddField(
            model_name="userdivisionteam",
            name="division",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member_division_teams",
                to="users.division",
                verbose_name="부서",
            ),
        ),
        migrations.AddField(
            model_name="userdivisionteam",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member_division_teams",
                to="users.team",
                verbose_name="팀",
            ),
        ),
        migrations.AddField(
            model_name="userdivisionteam",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="division_teams",
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
        migrations.AddField(
            model_name="userfunctionaldeptrole",
            name="functional_department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member_roles",
                to="users.functionaldepartment",
                verbose_name="일하는 부서",
            ),
        ),
        migrations.AddField(
            model_name="userfunctionaldeptrole",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="functional_dept_roles",
                to="users.role",
                verbose_name="직책",
            ),
        ),
        migrations.AddField(
            model_name="userfunctionaldeptrole",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="functional_dept_roles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
        migrations.RemoveField(
            model_name="memberrole",
            name="department",
        ),
        migrations.RemoveField(
            model_name="memberrole",
            name="role",
        ),
        migrations.RemoveField(
            model_name="memberrole",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="team",
            unique_together={("division", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="userclub",
            unique_together={("user", "club")},
        ),
        migrations.AddConstraint(
            model_name="userdivisionteam",
            constraint=models.UniqueConstraint(
                fields=("user", "division", "team"), name="unique_user_division_team"
            ),
        ),
        migrations.AddConstraint(
            model_name="userfunctionaldeptrole",
            constraint=models.UniqueConstraint(
                fields=("user", "functional_department", "role"),
                name="unique_user_funcdept_role",
            ),
        ),
        migrations.DeleteModel(
            name="Department",
        ),
        migrations.DeleteModel(
            name="MemberRole",
        ),
    ]
