# Generated by Django 6.0.3 on 2026-03-24 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="onboarding_note",
            field=models.TextField(blank=True, default="", verbose_name="온보딩 메모"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="onboarding_status",
            field=models.CharField(
                choices=[
                    ("pending", "승인 대기"),
                    ("approved", "승인 완료"),
                    ("rejected", "반려"),
                ],
                default="pending",
                max_length=20,
                verbose_name="온보딩 상태",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="requested_division",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_user_profiles",
                to="users.division",
                verbose_name="신청 부서",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="requested_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_user_profiles",
                to="users.team",
                verbose_name="신청 팀",
            ),
        ),
    ]
