# Generated by Django 6.0.3 on 2026-03-24 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userprofile_onboarding_note_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PastoralDivisionAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="주 담당"),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="정렬 순서"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pastoral_assignees",
                        to="users.division",
                        verbose_name="담당 부서",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pastoral_divisions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "목회 담당 부서",
                "verbose_name_plural": "목회 담당 부서",
                "ordering": [
                    "user",
                    "-is_primary",
                    "sort_order",
                    "division__sort_order",
                    "division__name",
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "division"),
                        name="unique_pastoral_user_division",
                    )
                ],
            },
        ),
    ]
