# Generated by Django 6.0.3 on 2026-04-05 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_userprofile_avatar_history"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalServiceClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.SlugField(
                        max_length=64, unique=True, verbose_name="연동 식별자"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="표시 이름"
                    ),
                ),
                (
                    "key_prefix",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=16
                    ),
                ),
                (
                    "key_hash",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=64
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="사용")),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="비고"),
                ),
            ],
            options={
                "verbose_name": "연동 API 클라이언트",
                "verbose_name_plural": "연동 API 클라이언트",
                "db_table": "users_externalserviceclient",
            },
        ),
    ]
