# Generated by Django 6.0.3 on 2026-06-02 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retreat", "0002_alter_retreatsession_options_and_more"),
        ("users", "0009_region_and_division_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="requested_retreat_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_user_profiles",
                to="retreat.retreatevent",
                verbose_name="희망 수련회",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="requested_retreat_participation",
            field=models.BooleanField(default=False, verbose_name="수련회 참여 희망"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="requested_retreat_role",
            field=models.CharField(
                blank=True,
                default="",
                help_text="participant | leader | vice_leader",
                max_length=20,
                verbose_name="수련회 희망 역할",
            ),
        ),
    ]
