# Generated by Django 6.0.3 on 2026-06-03 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retreat", "0017_profile_real_name_attendee_role"),
        ("users", "0010_userprofile_requested_retreat_event_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="real_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="본명(관리·승인 화면용)",
                max_length=50,
                verbose_name="실명",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="requested_retreat_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_user_profiles",
                to="retreat.retreatgroup",
                verbose_name="희망 수련회 조",
            ),
        ),
    ]
