# Generated by Django 6.0.3 on 2026-06-03 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_avatar_account_snapshots(apps, schema_editor):
    UserProfileAvatar = apps.get_model("users", "UserProfileAvatar")
    UserProfile = apps.get_model("users", "UserProfile")
    User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))
    for row in UserProfileAvatar.objects.exclude(user_profile_id=None).iterator():
        profile = UserProfile.objects.filter(pk=row.user_profile_id).first()
        if not profile or not profile.user_id:
            continue
        user = User.objects.filter(pk=profile.user_id).first()
        if not user:
            continue
        row.user_id_snapshot = user.id
        row.username_snapshot = user.username or ""
        row.save(update_fields=["user_id_snapshot", "username_snapshot"])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_profile_real_name_attendee_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofileavatar",
            name="user_id_snapshot",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                help_text="계정 삭제 후에도 이력 조회용으로 보존",
                null=True,
                verbose_name="계정 ID(스냅샷)",
            ),
        ),
        migrations.AddField(
            model_name="userprofileavatar",
            name="username_snapshot",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="username(스냅샷)"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="계정",
            ),
        ),
        migrations.AlterField(
            model_name="userprofileavatar",
            name="user_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="avatar_history",
                to="users.userprofile",
                verbose_name="프로필",
            ),
        ),
        migrations.RunPython(
            backfill_avatar_account_snapshots, migrations.RunPython.noop
        ),
    ]
