# Generated by Django 6.0.3 on 2026-06-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_user_signup_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="retired_at",
            field=models.DateTimeField(
                blank=True,
                help_text="탈퇴 처리된 계정. 물리 삭제 대신 신원 분리·비활성화.",
                null=True,
                verbose_name="탈퇴 일시",
            ),
        ),
    ]
