# Generated by Django 6.0.3 on 2026-06-16 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_user_retired_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="can_manage_notices",
            field=models.BooleanField(
                default=False,
                help_text="공지사항 작성·수정·삭제 권한",
                verbose_name="공지 관리 권한",
            ),
        ),
    ]
