# Generated by Django 6.0.3 on 2026-06-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_userprofile_interest_topics"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="requested_applicant_role",
            field=models.CharField(
                choices=[
                    ("member", "성도"),
                    ("pastor", "목사"),
                    ("evangelist", "전도사"),
                ],
                default="member",
                help_text="가입 신청서 구분용(목사/전도사/성도). User.role_level 과 별개.",
                max_length=20,
                verbose_name="신청 직급",
            ),
        ),
    ]
