# Generated by Django 6.0.3 on 2026-07-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_userprofile_requested_applicant_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "남성"), ("female", "여성")],
                default="",
                max_length=10,
                verbose_name="성별",
            ),
        ),
    ]
