from cryptography.fernet import Fernet as __Fernet

from ._crypto import key as __key

__f = __Fernet(__key)


def decode_encrypted_secret(value):
    return __f.decrypt(value.encode("utf-8")).decode("utf-8")


ENCRYPTED_SECRETS = {
    "DJANGO": {
        "DJANGO_SECRET_KEY": "gAAAAABni2tYOgqDE2B52XW4-Z5rQLnL8Pnn9HguvTXz9w_iR6Z4zqETowE7RST5RQCYcoEKyF8QawJ9uscNwrbaCwuwLrushq-Hz6A1sHgzHgCPIZKKMD2PzbHuU4_izXCo6l0Cyhnro8o8KXw7HTTvTw7mgx7j-0iO8XF6w8Jia-6H6PmVfi0=",
    },
    "DATABASE": {
        "DB_HOST_DEV": "gAAAAABni21sCbT_I6IvsTsfTTZQRyVHXiL4otnxB_Ge_XSyGnq0VAWlt84592rYjR7s9krPIDLYcl-Z_lOFlSVWOvGTTMaHew==",
        "DB_NAME_DEV": "gAAAAABqV5cWgPqB-qI5na8zQWlHKKprvfqfYyLUkCriZ5Q63EJNL4faQ3oEcF_w8hykq0xmDENB-0yS5ywFXiQKL6RuamfV9Q==",
        "DB_USERNAME_DEV": "gAAAAABqV5cn_J8i8c9WWcBCj0ZArxSuzUywKZVdmxVgZhe1V5IkBw37XJt1UFib_bQyBrukMIVbmzMx91jYTw7IXLFflOjMng==",
        "DB_PASSWORD_DEV": "gAAAAABqV5cdoEVREckJVdnlXiSJmhZ4e9D4tmsKcTWHFuvUzTcqqJFzUtvGkiBd-DFRLkEmCNKSnTXf8him9UKETigwY0soAQ==",
        "DB_PORT_DEV": "gAAAAABqV5cDr7SaMAiBum8a1AXR4YMoW4q2Y5EvfPnbEYCLvkx0MAiyKpOv8FFc3y780CW5OwehZI1VzKgVFyY8LjjH-iJKmQ==",
        "DB_HOST_PRODUCTION": "gAAAAABqV5dnSJFw1c64mrxjSEKijVTQlAbvkVB_4495cs1B4c1U7lIEF5_h6afwvPQtfWMAO51TwmJzA13B52KEpSph7UX10A==",
        "DB_NAME_PRODUCTION": "gAAAAABqV5d9v2S5dJueOqqH-Z1iGCifXtMW19rkQ5NbIHFubZhsWfGnDBKm_4I_3uhvDbZgsN9bYukHMN4MaQGX2ZQFZ35rzQ==",
        "DB_USERNAME_PRODUCTION": "gAAAAABqV5eBvKSCB1dJpB51dt8X8Mhl0KaB4Jedj6yqPnqa6jXl1mXLsy5BU87HS48lDDLsbRsbo2SFXiEjfLv1ko5TH8x2AQ==",
        "DB_PASSWORD_PRODUCTION": "gAAAAABqV5eLlIdfDkwWGtYKZBQfQ2SvU8P1ikraPTtAxdgGDbgYbjNkUKex2dVjC51jEf3bnx9ulUwiV9HUDpn2W5IrF5aPCA==",
        "DB_PORT_PRODUCTION": "gAAAAABqV5eX1DI3xp6oIEL-VsWisdJP0VUKJXpWOklDz1fP0PYM58GxD5qIsF8BQN5X4SFpv7qjowAC1Lg-FbDEis076lZMiA==",
        "RDS_HOST_PRODUCTION": "gAAAAABqWv-9UgYy_XSCflNL49n6w6Y_fc21yX3V9fdR041BTqZKFbL7b1JXJBpVaAyhoYMtihopVffm6bDWJwaf_5wahHsQO7UJeDGx_r0Y-fJwDFs7oUfsqc5ZS-w2_-ILJIqDxxlo7jr-ZcVlpkFhYyeTI2DDew==",
        "RDS_NAME_PRODUCTION": "gAAAAABqV5fY4-fGrBIgz8XAfkManEx126oW2GUuwlAeTSn2gqRGNSbjppsG6lHrZOIqzQ5kJQnO33W4y04w-6xARbQxEorXqQ==",
        "RDS_USERNAME_PRODUCTION": "gAAAAABqV5fdOGjg9H6MNSBYQiKuNvnILOkLm4oPFsWB0OOhlTN6n64Znu8b4--GdCWy4CqHkmkGSWLUA8P3CmeY0-qPeilR2A==",
        "RDS_PASSWORD_PRODUCTION": "gAAAAABqV5f7HwHAL5DxX1zK2KfRLHJ0zAZLgtiDaIjT3ZZKCy3nAsbc59D1WmqTIYNnF_UWBgw9BiEZI_MjfL2TlVplt7lu3g==",
        "RDS_PORT_PRODUCTION": "gAAAAABqV5gGw5QbtFvf8ChRFpjiluil3SfJbLAsmqDn6AmWME2UcKI3wE0dUzz02wkkwaAM_iXLuseUJK9wDhafxViULP84Ig==",
    },
    "SERVICE": {
        "RABBITMQ_PASSWORD": "gAAAAABqV5kkggI53SoG9GjMeQUYk9Dd4xmq08TY1XidjL6-dF5pMLSb97yxD6Kk4K8tH6DZmEuac2GjyRdKwey36ICPLioSXA==",
    },
    "AWS": {
        "S3_ACCESS_KEY_ID": "gAAAAABqVxDXWKWGCf8wtjc7HvxrU7sLbTye7mdEiWu-ZXIxAglzGWgqm1y2ljTnNDzhCJQ-_YbwGoNfXLZUHOvusyXwzdvEEnaxZmg475NR0x488gTRDxk=",
        "S3_SECRET_ACCESS_KEY": "gAAAAABqVxDz_3XDtla9KZGbD1zHtiise3HxcQXbZFR12PVk6erxv5hWk4UGnvhjOvtS2MSefTCS4eXGAhy0uI_ZHa9PMnUaP2VhF1rn2CWdFk0Obv1RVCj-UR787ueNxvW25kRHQocm",
        "S3_STORAGE_BUCKET_NAME": "gAAAAABqVxEhjnH555RYXeWyMHGg_iInmg1DUqg6gLJWtB_hfe5VUj5amY8jK-OjG-s4wlNVnKNEXKLvrFtV_fOSH2ymwoZ54A==",
        "S3_CUSTOM_DOMAIN": "gAAAAABqV1FOYZTNUBIcKtdnEcFIsl4kaBHWpfLLDrPxmh9yQitZns_xqooFe18tTrtDjn48Uk_kLtiL_B_P0rffGWWTs85PnuyMCo9M76rjEKIvBjKGp4g=",
    },
    "KAKAO": {
        "KAKAO_REST_API_KEY": "gAAAAABqV19xbL06Bfu7uAhHS8SMhtDr3IgeHUym3PFRyFElA1LaMaPLG0MJkhaUlp6rrt1lLH5TfVkBL-Xz7iwiSE9mT47VMF1Mf9Q1Brz8-xyLeaQp1k7aBRkhcpX0Q2SjYROhofAE",
        "KAKAO_CLIENT_SECRET": "gAAAAABqV1-IlmvBhlCD_reUj6DJqOiSdJWJIBPSgVV63BFUgt06Ex0fSc5tRaYl6-4mfAjnd1UPZMNMNH9DDRx9eAj75EW-LjVjov45e6h87SUQX9piGFH83hs6swh8OKlizX9vlf2B",
    },
    "API_TOKEN": {
        "RETREAT": "gAAAAABqXNxniUNaVKLS_nMSUETHTCA_A-H_xkXoU3RvpIFQGzat-g_RMIqXyPNTwSJ4C5urGjXQwATvN_hIvo7CKV-zUW4tzQ==",
    },
}

# DJANGO
DJANGO_SECRET_KEY = decode_encrypted_secret(ENCRYPTED_SECRETS["DJANGO"]["DJANGO_SECRET_KEY"])

# DATABASE
DB_HOST_DEV = decode_encrypted_secret(ENCRYPTED_SECRETS["DATABASE"]["DB_HOST_DEV"])
DB_NAME_DEV = decode_encrypted_secret(ENCRYPTED_SECRETS["DATABASE"]["DB_NAME_DEV"])
DB_USERNAME_DEV = decode_encrypted_secret(ENCRYPTED_SECRETS["DATABASE"]["DB_USERNAME_DEV"])
DB_PASSWORD_DEV = decode_encrypted_secret(ENCRYPTED_SECRETS["DATABASE"]["DB_PASSWORD_DEV"])
DB_PORT_DEV = decode_encrypted_secret(ENCRYPTED_SECRETS["DATABASE"]["DB_PORT_DEV"])
DB_HOST_PRODUCTION = decode_encrypted_secret(ENCRYPTED_SECRETS["DATABASE"]["DB_HOST_PRODUCTION"])
DB_NAME_PRODUCTION = decode_encrypted_secret(ENCRYPTED_SECRETS["DATABASE"]["DB_NAME_PRODUCTION"])
DB_USERNAME_PRODUCTION = decode_encrypted_secret(ENCRYPTED_SECRETS["DATABASE"]["DB_USERNAME_PRODUCTION"])
DB_PASSWORD_PRODUCTION = decode_encrypted_secret(ENCRYPTED_SECRETS["DATABASE"]["DB_PASSWORD_PRODUCTION"])
DB_PORT_PRODUCTION = decode_encrypted_secret(ENCRYPTED_SECRETS["DATABASE"]["DB_PORT_PRODUCTION"])
RDS_HOST_PRODUCTION = decode_encrypted_secret(ENCRYPTED_SECRETS["DATABASE"]["RDS_HOST_PRODUCTION"])
RDS_NAME_PRODUCTION = decode_encrypted_secret(ENCRYPTED_SECRETS["DATABASE"]["RDS_NAME_PRODUCTION"])
RDS_USERNAME_PRODUCTION = decode_encrypted_secret(ENCRYPTED_SECRETS["DATABASE"]["RDS_USERNAME_PRODUCTION"])
RDS_PASSWORD_PRODUCTION = decode_encrypted_secret(ENCRYPTED_SECRETS["DATABASE"]["RDS_PASSWORD_PRODUCTION"])
RDS_PORT_PRODUCTION = decode_encrypted_secret(ENCRYPTED_SECRETS["DATABASE"]["RDS_PORT_PRODUCTION"])

# SERVICE
RABBITMQ_PASSWORD = decode_encrypted_secret(ENCRYPTED_SECRETS["SERVICE"]["RABBITMQ_PASSWORD"])

# AWS
S3_ACCESS_KEY_ID = decode_encrypted_secret(ENCRYPTED_SECRETS["AWS"]["S3_ACCESS_KEY_ID"])
S3_SECRET_ACCESS_KEY = decode_encrypted_secret(ENCRYPTED_SECRETS["AWS"]["S3_SECRET_ACCESS_KEY"])
S3_STORAGE_BUCKET_NAME = decode_encrypted_secret(ENCRYPTED_SECRETS["AWS"]["S3_STORAGE_BUCKET_NAME"])
S3_CUSTOM_DOMAIN = decode_encrypted_secret(ENCRYPTED_SECRETS["AWS"]["S3_CUSTOM_DOMAIN"])

# KAKAO
KAKAO_REST_API_KEY = decode_encrypted_secret(ENCRYPTED_SECRETS["KAKAO"]["KAKAO_REST_API_KEY"])
KAKAO_CLIENT_SECRET = decode_encrypted_secret(ENCRYPTED_SECRETS["KAKAO"]["KAKAO_CLIENT_SECRET"])

# API_TOKEN
RETREAT = decode_encrypted_secret(ENCRYPTED_SECRETS["API_TOKEN"]["RETREAT"])


all_secrets = locals()


def show_secrets():
    for key in [key for key in all_secrets if not key.startswith("__") and key != "ENCRYPTED_SECRETS" and key.isupper()]:
        value = all_secrets[key]
        print(f"{key}\n {value}\n")
