from . import _secrets as secrets

DB_HOST_DEV = secrets.DB_HOST_DEV
DB_NAME_DEV = secrets.DB_NAME_DEV
DB_USERNAME_DEV = secrets.DB_USERNAME_DEV
DB_PASSWORD_DEV = secrets.DB_PASSWORD_DEV
DB_PORT_DEV = secrets.DB_PORT_DEV

DB_HOST_PRODUCTION = secrets.DB_HOST_PRODUCTION
DB_NAME_PRODUCTION = secrets.DB_NAME_PRODUCTION
DB_USERNAME_PRODUCTION = secrets.DB_USERNAME_PRODUCTION
DB_PASSWORD_PRODUCTION = secrets.DB_PASSWORD_PRODUCTION
DB_PORT_PRODUCTION = secrets.DB_PORT_PRODUCTION

RDS_HOST_PRODUCTION = secrets.RDS_HOST_PRODUCTION
RDS_NAME_PRODUCTION = secrets.RDS_NAME_PRODUCTION
RDS_USERNAME_PRODUCTION = secrets.RDS_USERNAME_PRODUCTION
RDS_PASSWORD_PRODUCTION = secrets.RDS_PASSWORD_PRODUCTION
RDS_PORT_PRODUCTION = secrets.RDS_PORT_PRODUCTION
