# Generated by Django 6.0.3 on 2026-03-22 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("registry", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceWeek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "week_sunday",
                    models.DateField(
                        help_text="이 출석 주차를 식별하는 주일 날짜(해당 주의 주일).",
                        verbose_name="기준 주일",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="비고"
                    ),
                ),
                (
                    "auto_created",
                    models.BooleanField(
                        default=False,
                        help_text="ensure_weekly_attendance_weeks 등으로 생성된 경우 True",
                        verbose_name="자동 생성됨",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최초 등록자",
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_weeks",
                        to="users.division",
                        verbose_name="부서",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최종 수정자",
                    ),
                ),
            ],
            options={
                "verbose_name": "주간 출석(주차)",
                "verbose_name_plural": "주간 출석(주차)",
                "db_table": "users_attendanceweek",
                "ordering": ["-week_sunday", "division"],
            },
        ),
        migrations.CreateModel(
            name="MidweekAttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("wednesday", "수요일 예배"),
                            ("saturday", "토요일 예배"),
                        ],
                        max_length=20,
                        verbose_name="예배",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("present", "참석"),
                            ("absent", "불참"),
                            ("online", "온라인"),
                        ],
                        help_text="비우면 아직 미입력",
                        max_length=20,
                        null=True,
                        verbose_name="출석",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최초 등록자",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="midweek_attendance_records",
                        to="registry.member",
                        verbose_name="멤버",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최종 수정자",
                    ),
                ),
                (
                    "week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="midweek_records",
                        to="attendance.attendanceweek",
                        verbose_name="주차",
                    ),
                ),
            ],
            options={
                "verbose_name": "수·토 출석",
                "verbose_name_plural": "수·토 출석",
                "db_table": "users_midweekattendancerecord",
                "ordering": ["week", "service_type", "member__name"],
            },
        ),
        migrations.CreateModel(
            name="SundayAttendanceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "venue",
                    models.CharField(
                        choices=[
                            ("incheon", "인천 예배"),
                            ("seoul", "서울 예배"),
                            ("online", "온라인"),
                            ("branch", "지교회"),
                        ],
                        max_length=20,
                        verbose_name="주일 구분",
                    ),
                ),
                (
                    "session_part",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="서울/인천 1~4부. 온라인·지교회는 0.",
                        verbose_name="부",
                    ),
                ),
                (
                    "branch_label",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="지교회 표기",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최초 등록자",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sunday_attendance_lines",
                        to="registry.member",
                        verbose_name="멤버",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sunday_attendance_lines",
                        to="users.team",
                        verbose_name="팀",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최종 수정자",
                    ),
                ),
                (
                    "week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sunday_lines",
                        to="attendance.attendanceweek",
                        verbose_name="주차",
                    ),
                ),
            ],
            options={
                "verbose_name": "주일 출석(행)",
                "verbose_name_plural": "주일 출석(행)",
                "db_table": "users_sundayattendanceline",
                "ordering": ["week", "member__name", "venue", "session_part"],
            },
        ),
        migrations.CreateModel(
            name="TeamAttendanceSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_date", models.DateField(verbose_name="날짜")),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="비우면 앱에서 팀명+출석부로 표시",
                        max_length=120,
                        verbose_name="제목",
                    ),
                ),
                (
                    "period_count",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="1교시·2교시 … (최대 20)",
                        verbose_name="교시 수",
                    ),
                ),
                (
                    "period_labels",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='비우면 ["1교시","2교시",…]',
                        verbose_name="교시 라벨",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="메모"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attendance_week",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team_sessions",
                        to="attendance.attendanceweek",
                        verbose_name="연결 주차(선택)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최초 등록자",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_sessions",
                        to="users.team",
                        verbose_name="팀",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최종 수정자",
                    ),
                ),
            ],
            options={
                "verbose_name": "팀 출석(회차)",
                "verbose_name_plural": "팀 출석(회차)",
                "db_table": "users_teamattendancesession",
                "ordering": ["-session_date", "team"],
            },
        ),
        migrations.CreateModel(
            name="TeamMemberSlotAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slot_index",
                    models.PositiveSmallIntegerField(
                        help_text="1 = 1교시", verbose_name="교시 번호"
                    ),
                ),
                (
                    "picks",
                    models.JSONField(blank=True, default=list, verbose_name="선택(칩)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최초 등록자",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_slot_attendances",
                        to="registry.member",
                        verbose_name="멤버(교적)",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slot_rows",
                        to="attendance.teamattendancesession",
                        verbose_name="팀 출석 회차",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최종 수정자",
                    ),
                ),
            ],
            options={
                "verbose_name": "팀 출석 교시(칩)",
                "verbose_name_plural": "팀 출석 교시(칩)",
                "db_table": "users_teammemberslotattendance",
                "ordering": ["session", "member__name", "slot_index"],
            },
        ),
        migrations.CreateModel(
            name="WorshipRosterScope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "venue",
                    models.CharField(
                        choices=[
                            ("incheon", "인천 예배"),
                            ("seoul", "서울 예배"),
                            ("online", "온라인"),
                            ("branch", "지교회"),
                        ],
                        max_length=20,
                        verbose_name="예배 구분",
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        help_text="예: 2024", verbose_name="연도"
                    ),
                ),
                (
                    "session_part",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="1~4부. 인천(미구분 시 기본 3). 온라인/지교회는 0.",
                        verbose_name="부",
                    ),
                ),
                (
                    "branch_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="지교회일 때 하위 폴더명 등 (서울/인천/온라인은 보통 비움)",
                        max_length=100,
                        verbose_name="지교회 표기",
                    ),
                ),
                (
                    "snapshot_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="한 파일에 주차별 시트가 여러 개일 때 구분.",
                        max_length=200,
                        verbose_name="스냅샷(시트) 구분",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="정렬"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최초 등록자",
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worship_roster_scopes",
                        to="users.division",
                        verbose_name="부서",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최종 수정자",
                    ),
                ),
            ],
            options={
                "verbose_name": "출석 명단 구분",
                "verbose_name_plural": "출석 명단 구분",
                "db_table": "users_worshiprosterscope",
                "ordering": [
                    "-year",
                    "venue",
                    "session_part",
                    "branch_label",
                    "snapshot_label",
                ],
            },
        ),
        migrations.CreateModel(
            name="WorshipRosterEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_rel_path",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="원본 파일(상대경로)",
                    ),
                ),
                (
                    "sheet_name",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="시트명"
                    ),
                ),
                (
                    "first_imported_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="최초 반영 시각"
                    ),
                ),
                (
                    "last_imported_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="마지막 반영 시각"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최초 등록자",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worship_roster_entries",
                        to="registry.member",
                        verbose_name="멤버",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        help_text="엑셀 팀 열 기준",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="worship_roster_entries",
                        to="users.team",
                        verbose_name="팀",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="최종 수정자",
                    ),
                ),
                (
                    "scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="attendance.worshiprosterscope",
                        verbose_name="명단 구분",
                    ),
                ),
            ],
            options={
                "verbose_name": "출석 명단 구성원",
                "verbose_name_plural": "출석 명단 구성원",
                "db_table": "users_worshiprosterentry",
                "ordering": ["scope", "member__name"],
            },
        ),
        migrations.AddConstraint(
            model_name="attendanceweek",
            constraint=models.UniqueConstraint(
                fields=("division", "week_sunday"),
                name="uniq_attendance_week_division_sunday",
            ),
        ),
        migrations.AddConstraint(
            model_name="midweekattendancerecord",
            constraint=models.UniqueConstraint(
                fields=("week", "member", "service_type"),
                name="uniq_midweek_week_member_service",
            ),
        ),
        migrations.AddConstraint(
            model_name="sundayattendanceline",
            constraint=models.UniqueConstraint(
                fields=("week", "member", "venue", "session_part", "branch_label"),
                name="uniq_sunday_line_week_member_venue_part_branch",
            ),
        ),
        migrations.AddConstraint(
            model_name="teamattendancesession",
            constraint=models.UniqueConstraint(
                fields=("team", "session_date"), name="uniq_team_attendance_team_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="teammemberslotattendance",
            constraint=models.UniqueConstraint(
                fields=("session", "member", "slot_index"),
                name="uniq_team_slot_session_member_index",
            ),
        ),
        migrations.AddConstraint(
            model_name="worshiprosterscope",
            constraint=models.UniqueConstraint(
                fields=(
                    "division",
                    "venue",
                    "year",
                    "session_part",
                    "branch_label",
                    "snapshot_label",
                ),
                name="uniq_worship_roster_scope_div_venue_year_part_branch_snap",
            ),
        ),
        migrations.AddConstraint(
            model_name="worshiprosterentry",
            constraint=models.UniqueConstraint(
                fields=("scope", "member"),
                name="uniq_worship_roster_entry_scope_member",
            ),
        ),
    ]
