# Generated by Django 6.0.3 on 2026-03-24 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_team_name_snapshot"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="midweekattendancerecord",
            new_name="users_midwe_divisio_80ccfe_idx",
            old_name="users_midwe_division_8f1b2d_idx",
        ),
        migrations.RenameIndex(
            model_name="sundayattendanceline",
            new_name="users_sunda_divisio_4aaf88_idx",
            old_name="users_sunda_division_9c2e3e_idx",
        ),
    ]
