# Generated by Django 6.0.3 on 2026-03-24 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "attendance",
            "0006_rename_users_midwe_division_8f1b2d_idx_users_midwe_divisio_80ccfe_idx_and_more",
        ),
        ("users", "0003_pastoraldivisionassignment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ParkingPermitApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_number",
                    models.CharField(max_length=30, verbose_name="차량번호"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "신청"),
                            ("approved", "승인"),
                            ("rejected", "반려"),
                        ],
                        default="submitted",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="메모"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="신청일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "division",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parking_permit_applications",
                        to="users.division",
                        verbose_name="소속 부서",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parking_permit_applications",
                        to="users.team",
                        verbose_name="소속 팀",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parking_permit_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="신청자",
                    ),
                ),
            ],
            options={
                "verbose_name": "주차권 신청",
                "verbose_name_plural": "주차권 신청",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "vehicle_number"),
                        name="unique_user_vehicle_number",
                    )
                ],
            },
        ),
    ]
