# Generated by Django 6.0.3 on 2026-03-31 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0009_parkingpermitwindow"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="parkingpermitwindow",
            new_name="attendance__divisio_14bd69_idx",
            old_name="attendance_p_division_2f4c8e_idx",
        ),
    ]
